# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/157_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_157_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 21.6
KAB = 48.17
KAC = 418.82
KAD = 11.66
KAE = 14.69
KAF = 11.66
KAG = 121.61
KAH = 8.64
KAI = 99.14
KAJ = 13.39
KAK = 27.0
KAL = 40.39
KAM = 22.25
KAN = 190.94
KAO = 174.31
KAP = 14.47
KAQ = 11.88
KAR = 21.17
KAS = 47.52
KAT = 16.85
KAU = 15.55
KAV = 147.31
KAW = 9.5
KAX = 149.9
KAY = 128.09
KAZ = 10.8
KBA = 127.66
KBB = 25.7
KBC = 62.86
KBD = 29.59
KBE = 67.61

[RESULTS.AREA]
KAA = 27.96
KAB = 50.53
KAC = 326.64
KAD = 21.45
KAE = 25.34
KAF = 21.09
KAG = 116.43
KAH = 12.49
KAI = 53.33
KAJ = 14.91
KAK = 24.77
KAL = 66.14
KAM = 31.29
KAN = 141.87
KAO = 112.9
KAP = 24.96
KAQ = 25.62
KAR = 42.63
KAS = 41.77
KAT = 35.41
KAU = 31.32
KAV = 102.88
KAW = 10.86
KAX = 150.11
KAY = 144.63
KAZ = 14.5
KBA = 80.21
KBB = 21.92
KBC = 66.48
KBD = 39.04
KBE = 58.67

[RESULTS.MAX_DEPTH]
KAA = 0.6
KAB = 2.47
KAC = 2.47
KAD = 1.34
KAE = 1.04
KAF = 0.6
KAG = 3.55
KAH = 0.85
KAI = 1.99
KAJ = 0.6
KAK = 1.2
KAL = 0.85
KAM = 1.2
KAN = 2.75
KAO = 3.0
KAP = 1.7
KAQ = 0.85
KAR = 0.0
KAS = 2.4
KAT = 0.0
KAU = 1.2
KAV = 1.47
KAW = 0.6
KAX = 2.62
KAY = 6.12
KAZ = 0.85
KBA = 1.8
KBB = 0.6
KBC = 2.47
KBD = 1.34
KBE = 2.81

[RESULTS.AVG_DEPTH]
KAA = 0.09
KAB = 0.63
KAC = 0.85
KAD = 0.48
KAE = 0.34
KAF = 0.21
KAG = 1.0
KAH = 0.2
KAI = 0.51
KAJ = 0.05
KAK = 0.2
KAL = 0.17
KAM = 0.32
KAN = 0.71
KAO = 0.66
KAP = 0.59
KAQ = 0.2
KAR = 0.0
KAS = 0.52
KAT = 0.0
KAU = 0.29
KAV = 0.51
KAW = 0.1
KAX = 0.92
KAY = 2.6
KAZ = 0.25
KBA = 0.46
KBB = 0.18
KBC = 0.7
KBD = 0.48
KBE = 0.6

[RESULTS.AVG_HYDROPATHY]
KAA = 0.7
KAB = -0.18
KAC = 0.13
KAD = 0.09
KAE = -0.59
KAF = -0.38
KAG = 0.04
KAH = 0.2
KAI = 0.03
KAJ = 0.13
KAK = 0.52
KAL = -0.45
KAM = -0.09
KAN = -0.27
KAO = 0.39
KAP = 1.19
KAQ = 0.68
KAR = -0.08
KAS = 0.79
KAT = 0.32
KAU = 0.04
KAV = 0.1
KAW = -0.36
KAX = -0.04
KAY = 0.05
KAZ = 0.55
KBA = -0.32
KBB = 0.85
KBC = 0.37
KBD = -0.64
KBE = -0.3
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "385", " ", "ALA",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "393", " ", "LEU",],]
KAB = [ [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",],]
KAC = [ [ "219", " ", "THR",], [ "220", " ", "SER",], [ "221", " ", "SER",], [ "222", " ", "LYS",], [ "224", " ", "ASN",], [ "229", " ", "THR",], [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",],]
KAD = [ [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "181", " ", "LEU",], [ "182", " ", "LYS",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "186", " ", "SER",], [ "187", " ", "GLU",],]
KAE = [ [ "172", " ", "PRO",], [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",], [ "178", " ", "SER",], [ "184", " ", "ILE",], [ "187", " ", "GLU",],]
KAF = [ [ "408", " ", "TYR",], [ "412", " ", "ALA",], [ "414", " ", "LEU",], [ "416", " ", "GLY",], [ "417", " ", "ALA",], [ "418", " ", "GLY",], [ "420", " ", "ALA",],]
KAG = [ [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",],]
KAH = [ [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "200", " ", "GLU",],]
KAI = [ [ "318", " ", "LYS",], [ "333", " ", "ALA",], [ "334", " ", "GLY",], [ "335", " ", "SER",], [ "336", " ", "SER",], [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "361", " ", "SER",], [ "362", " ", "ARG",], [ "363", " ", "ASP",], [ "364", " ", "TYR",], [ "365", " ", "TYR",],]
KAJ = [ [ "311", " ", "PRO",], [ "312", " ", "PHE",], [ "313", " ", "LYS",], [ "341", " ", "LEU",],]
KAK = [ [ "594", " ", "TYR",], [ "596", " ", "CYS",], [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "618", " ", "ARG",],]
KAL = [ [ "432", " ", "SER",], [ "434", " ", "SER",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "442", " ", "GLU",], [ "443", " ", "GLU",],]
KAM = [ [ "433", " ", "SER",], [ "434", " ", "SER",], [ "435", " ", "TRP",], [ "531", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",],]
KAN = [ [ "451", " ", "GLY",], [ "452", " ", "GLY",], [ "453", " ", "GLY",], [ "454", " ", "GLY",], [ "520", " ", "VAL",], [ "521", " ", "LYS",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",],]
KAO = [ [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "543", " ", "ALA",], [ "544", " ", "ARG",], [ "545", " ", "ASP",], [ "546", " ", "HIS",], [ "548", " ", "LEU",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "606", " ", "LYS",], [ "639", " ", "LEU",],]
KAP = [ [ "583", " ", "PHE",], [ "610", " ", "LYS",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "613", " ", "PRO",], [ "615", " ", "CYS",], [ "616", " ", "ARG",],]
KAQ = [ [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "564", " ", "GLY",], [ "565", " ", "ASP",], [ "604", " ", "ILE",], [ "605", " ", "ASP",], [ "606", " ", "LYS",], [ "609", " ", "ARG",],]
KAR = [ [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "580", " ", "CYS",], [ "583", " ", "PHE",], [ "584", " ", "PHE",], [ "616", " ", "ARG",], [ "620", " ", "CYS",],]
KAS = [ [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",],]
KAT = [ [ "563", " ", "CYS",], [ "579", " ", "SER",], [ "580", " ", "CYS",], [ "583", " ", "PHE",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "616", " ", "ARG",],]
KAU = [ [ "558", " ", "LYS",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "639", " ", "LEU",],]
KAV = [ [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "628", " ", "GLY",], [ "629", " ", "GLU",], [ "630", " ", "LYS",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",],]
KAW = [ [ "466", " ", "GLY",], [ "467", " ", "GLY",], [ "468", " ", "GLY",], [ "491", " ", "ALA",], [ "492", " ", "GLY",], [ "493", " ", "GLN",], [ "494", " ", "GLU",],]
KAX = [ [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",],]
KAY = [ [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "575", " ", "LEU",], [ "576", " ", "THR",], [ "577", " ", "CYS",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",],]
KAZ = [ [ "460", " ", "GLY",], [ "462", " ", "GLY",], [ "463", " ", "GLY",], [ "494", " ", "GLU",], [ "495", " ", "SER",], [ "496", " ", "ASP",],]
KBA = [ [ "457", " ", "GLY",], [ "458", " ", "GLY",], [ "460", " ", "GLY",], [ "496", " ", "ASP",], [ "497", " ", "PHE",], [ "498", " ", "THR",], [ "499", " ", "ALA",], [ "500", " ", "PRO",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "513", " ", "PRO",], [ "514", " ", "TYR",], [ "515", " ", "PRO",], [ "644", " ", "PRO",],]
KBB = [ [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",],]
KBC = [ [ "501", " ", "ASP",], [ "502", " ", "VAL",], [ "503", " ", "TRP",], [ "504", " ", "TYR",], [ "505", " ", "PRO",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "514", " ", "TYR",],]
KBD = [ [ "49", " ", "PRO",], [ "50", " ", "PRO",], [ "51", " ", "GLY",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "57", " ", "LEU",],]
KBE = [ [ "20", " ", "ARG",], [ "21", " ", "GLY",], [ "22", " ", "ALA",], [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "30", " ", "VAL",], [ "31", " ", "ARG",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
GLU = 1
ILE = 1
LEU = 2
LYS = 1
PRO = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 0
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 3
ASP = 1
GLY = 1
LEU = 1
PRO = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 2
R3 = 0
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 2
ASN = 1
ASP = 1
CYS = 1
GLU = 3
GLY = 1
HIS = 1
ILE = 1
LEU = 3
LYS = 3
SER = 4
THR = 2
VAL = 2

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 9
R2 = 0
R3 = 8
R4 = 4
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ASP = 1
GLU = 1
ILE = 1
LEU = 1
LYS = 1
SER = 2

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
GLU = 1
GLY = 1
ILE = 1
LEU = 1
PRO = 1
SER = 3

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 4
R2 = 0
R3 = 3
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 3
GLY = 2
LEU = 1
TYR = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 6
R2 = 1
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 1
GLN = 5
GLU = 1
LEU = 3
MET = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 4
R2 = 0
R3 = 9
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
GLN = 3
GLU = 1
LEU = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLN = 1
GLY = 1
LYS = 1
SER = 3
TYR = 3

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 2
R2 = 3
R3 = 4
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
LEU = 1
LYS = 1
PHE = 1
PRO = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 2
R2 = 1
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ARG = 2
ASN = 1
CYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 0
R2 = 1
R3 = 3
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 1
GLU = 2
HIS = 1
LEU = 1
PHE = 1
SER = 2
THR = 2

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 2
R2 = 1
R3 = 4
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ARG = 1
ASP = 1
GLY = 1
MET = 1
SER = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 1
R2 = 2
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ASP = 1
GLY = 7
LYS = 1
MET = 1
PRO = 2
SER = 2
TRP = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 10
R2 = 3
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLN = 1
GLU = 1
HIS = 1
LEU = 3
LYS = 2
PRO = 1
THR = 2

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 5
R2 = 0
R3 = 3
R4 = 2
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ARG = 1
ASN = 1
CYS = 2
LYS = 1
PHE = 1
PRO = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 1
R2 = 1
R3 = 3
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ARG = 1
ASP = 2
CYS = 1
GLY = 1
ILE = 1
LYS = 1
THR = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ARG = 1
CYS = 3
ILE = 1
PHE = 2

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 1
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
GLN = 6
GLU = 1
THR = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ARG = 2
CYS = 2
LYS = 1
PHE = 1
SER = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 0
R2 = 1
R3 = 3
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
ASN = 1
CYS = 1
GLY = 1
LEU = 2
LYS = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 4
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 1
GLU = 1
GLY = 3
LYS = 1
MET = 1
PHE = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 5
R2 = 2
R3 = 4
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
GLN = 1
GLU = 1
GLY = 4

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 5
R2 = 0
R3 = 1
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ASP = 1
GLN = 1
HIS = 1
ILE = 1
LEU = 2
LYS = 1
MET = 1
PHE = 1
PRO = 3
TYR = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 6
R2 = 2
R3 = 2
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 1
ASN = 1
CYS = 3
GLN = 1
GLY = 1
HIS = 1
LEU = 2
LYS = 2
SER = 1
THR = 2

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 4
R2 = 0
R3 = 8
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ASP = 1
GLU = 1
GLY = 3
SER = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLY = 3
PHE = 1
PRO = 4
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 9
R2 = 2
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
GLN = 7

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ARG = 1
ASP = 1
PRO = 1
SER = 1
TRP = 1
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 3
R2 = 3
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBD.RESIDUES]
GLY = 1
LEU = 3
PRO = 2
SER = 1

[RESULTS.FREQUENCY.KBD.CLASS]
R1 = 6
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBE.RESIDUES]
ALA = 1
ARG = 2
ASN = 1
GLN = 1
GLY = 1
LEU = 1
PHE = 1
VAL = 1

[RESULTS.FREQUENCY.KBE.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 0
R5 = 2
RX = 0
