# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/53_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_53_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 156.17
KAB = 85.75
KAC = 6.26
KAD = 21.82
KAE = 106.7
KAF = 10.8
KAG = 12.74
KAH = 52.92
KAI = 13.61
KAJ = 311.47
KAK = 12.31
KAL = 25.27
KAM = 13.61
KAN = 12.31
KAO = 13.18
KAP = 18.36
KAQ = 245.16
KAR = 27.0
KAS = 7.13
KAT = 1632.53
KAU = 19.87
KAV = 1261.22
KAW = 5.18
KAX = 393.55
KAY = 170.64
KAZ = 46.01
KBA = 17.28
KBB = 9.72
KBC = 11.45
KBD = 22.03
KBE = 36.94

[RESULTS.AREA]
KAA = 99.47
KAB = 105.63
KAC = 12.51
KAD = 31.69
KAE = 121.21
KAF = 9.72
KAG = 23.54
KAH = 74.46
KAI = 10.76
KAJ = 318.85
KAK = 30.58
KAL = 48.55
KAM = 19.25
KAN = 30.58
KAO = 28.2
KAP = 25.41
KAQ = 227.42
KAR = 32.67
KAS = 16.09
KAT = 1044.73
KAU = 22.3
KAV = 952.78
KAW = 12.43
KAX = 243.51
KAY = 112.89
KAZ = 57.84
KBA = 31.36
KBB = 15.27
KBC = 17.98
KBD = 47.72
KBE = 57.1

[RESULTS.MAX_DEPTH]
KAA = 1.8
KAB = 2.47
KAC = 0.6
KAD = 2.55
KAE = 4.2
KAF = 0.6
KAG = 1.2
KAH = 2.55
KAI = 0.85
KAJ = 4.33
KAK = 0.0
KAL = 0.0
KAM = 0.85
KAN = 0.0
KAO = 1.34
KAP = 1.2
KAQ = 3.06
KAR = 1.7
KAS = 0.85
KAT = 5.16
KAU = 0.6
KAV = 7.35
KAW = 0.6
KAX = 4.28
KAY = 2.16
KAZ = 2.24
KBA = 1.34
KBB = 0.85
KBC = 0.6
KBD = 0.85
KBE = 1.8

[RESULTS.AVG_DEPTH]
KAA = 0.39
KAB = 0.92
KAC = 0.12
KAD = 0.92
KAE = 1.32
KAF = 0.02
KAG = 0.32
KAH = 0.73
KAI = 0.11
KAJ = 0.74
KAK = 0.0
KAL = 0.0
KAM = 0.18
KAN = 0.0
KAO = 0.33
KAP = 0.35
KAQ = 0.92
KAR = 0.51
KAS = 0.27
KAT = 1.53
KAU = 0.07
KAV = 1.82
KAW = 0.18
KAX = 0.95
KAY = 0.58
KAZ = 0.77
KBA = 0.35
KBB = 0.1
KBC = 0.07
KBD = 0.12
KBE = 0.49

[RESULTS.AVG_HYDROPATHY]
KAA = 0.01
KAB = -0.03
KAC = 0.17
KAD = -0.47
KAE = 0.29
KAF = -0.87
KAG = -0.4
KAH = -0.38
KAI = -0.45
KAJ = -0.44
KAK = 0.66
KAL = 1.17
KAM = -0.37
KAN = -0.81
KAO = -0.11
KAP = -0.35
KAQ = -0.07
KAR = 1.16
KAS = 0.88
KAT = -0.14
KAU = 0.28
KAV = 0.41
KAW = -0.73
KAX = -0.27
KAY = -0.01
KAZ = 0.7
KBA = -0.43
KBB = -0.12
KBC = -0.68
KBD = -0.37
KBE = -0.36
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "228", " ", "GLY",], [ "229", " ", "THR",], [ "230", " ", "SER",], [ "231", " ", "THR",], [ "232", " ", "ILE",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "271", " ", "PRO",],]
KAB = [ [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "244", " ", "SER",], [ "247", " ", "MET",], [ "248", " ", "GLY",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "254", " ", "LEU",], [ "255", " ", "GLU",],]
KAC = [ [ "197", " ", "GLN",], [ "199", " ", "GLN",], [ "201", " ", "ALA",], [ "202", " ", "VAL",], [ "203", " ", "SER",],]
KAD = [ [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "172", " ", "PRO",], [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "178", " ", "SER",], [ "179", " ", "ALA",],]
KAE = [ [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "566", " ", "GLU",], [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "575", " ", "LEU",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "639", " ", "LEU",],]
KAF = [ [ "132", " ", "VAL",], [ "137", " ", "ALA",], [ "138", " ", "ALA",], [ "139", " ", "VAL",], [ "140", " ", "ALA",],]
KAG = [ [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "168", " ", "GLY",], [ "169", " ", "PRO",], [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "178", " ", "SER",],]
KAH = [ [ "167", " ", "LEU",], [ "177", " ", "CYS",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",],]
KAI = [ [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "534", " ", "PRO",],]
KAJ = [ [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "561", " ", "LEU",], [ "570", " ", "CYS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "589", " ", "GLU",], [ "623", " ", "ALA",], [ "624", " ", "GLY",], [ "626", " ", "THR",], [ "627", " ", "LEU",], [ "628", " ", "GLY",], [ "629", " ", "GLU",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",],]
KAK = [ [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "580", " ", "CYS",], [ "604", " ", "ILE",], [ "609", " ", "ARG",], [ "616", " ", "ARG",],]
KAL = [ [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "608", " ", "ARG",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "615", " ", "CYS",], [ "616", " ", "ARG",],]
KAM = [ [ "523", " ", "GLU",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",],]
KAN = [ [ "562", " ", "ILE",], [ "571", " ", "HIS",], [ "572", " ", "TYR",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "576", " ", "THR",], [ "625", " ", "MET",],]
KAO = [ [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "612", " ", "CYS",], [ "614", " ", "SER",], [ "615", " ", "CYS",],]
KAP = [ [ "587", " ", "ALA",], [ "588", " ", "ALA",], [ "590", " ", "GLY",], [ "592", " ", "GLN",], [ "594", " ", "TYR",], [ "617", " ", "LEU",], [ "621", " ", "TYR",],]
KAQ = [ [ "310", " ", "SER",], [ "311", " ", "PRO",], [ "312", " ", "PHE",], [ "313", " ", "LYS",], [ "314", " ", "GLY",], [ "315", " ", "GLY",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "455", " ", "GLY",], [ "456", " ", "GLY",], [ "457", " ", "GLY",], [ "458", " ", "GLY",], [ "593", " ", "LYS",], [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "618", " ", "ARG",],]
KAR = [ [ "2", " ", "GLU",], [ "3", " ", "VAL",], [ "4", " ", "GLN",], [ "7", " ", "LEU",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",],]
KAS = [ [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "88", " ", "GLN",],]
KAT = [ [ "303", " ", "THR",], [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "312", " ", "PHE",], [ "313", " ", "LYS",], [ "314", " ", "GLY",], [ "315", " ", "GLY",], [ "316", " ", "TYR",], [ "317", " ", "THR",], [ "318", " ", "LYS",], [ "319", " ", "GLY",], [ "320", " ", "LEU",], [ "321", " ", "GLU",], [ "325", " ", "LEU",], [ "344", " ", "THR",], [ "345", " ", "LEU",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "351", " ", "GLY",], [ "352", " ", "ALA",], [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "355", " ", "GLU",], [ "356", " ", "ALA",], [ "432", " ", "SER",], [ "433", " ", "SER",], [ "434", " ", "SER",], [ "435", " ", "TRP",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "442", " ", "GLU",], [ "443", " ", "GLU",], [ "444", " ", "GLY",], [ "445", " ", "GLN",], [ "446", " ", "LEU",], [ "447", " ", "TYR",], [ "448", " ", "GLY",], [ "449", " ", "PRO",], [ "450", " ", "CYS",], [ "451", " ", "GLY",], [ "452", " ", "GLY",], [ "453", " ", "GLY",], [ "475", " ", "ALA",], [ "476", " ", "GLY",], [ "477", " ", "ALA",], [ "484", " ", "THR",], [ "485", " ", "ARG",], [ "486", " ", "PRO",], [ "487", " ", "PRO",], [ "488", " ", "GLN",], [ "489", " ", "GLY",], [ "490", " ", "LEU",], [ "491", " ", "ALA",], [ "492", " ", "GLY",], [ "493", " ", "GLN",], [ "494", " ", "GLU",], [ "495", " ", "SER",],]
KAU = [ [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "306", " ", "THR",], [ "307", " ", "ALA",], [ "308", " ", "GLU",], [ "309", " ", "TYR",], [ "310", " ", "SER",], [ "312", " ", "PHE",],]
KAV = [ [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "88", " ", "GLN",], [ "89", " ", "GLN",], [ "92", " ", "GLY",], [ "93", " ", "GLU",], [ "94", " ", "ASP",], [ "95", " ", "GLY",], [ "96", " ", "SER",], [ "97", " ", "PRO",], [ "98", " ", "GLN",], [ "99", " ", "ALA",], [ "100", " ", "HIS",], [ "101", " ", "ARG",], [ "102", " ", "ARG",], [ "103", " ", "GLY",], [ "104", " ", "PRO",], [ "105", " ", "THR",], [ "106", " ", "GLY",], [ "107", " ", "TYR",], [ "108", " ", "LEU",], [ "109", " ", "VAL",], [ "110", " ", "LEU",], [ "111", " ", "ASP",], [ "112", " ", "GLU",], [ "113", " ", "GLU",], [ "114", " ", "GLN",], [ "115", " ", "GLN",], [ "116", " ", "PRO",], [ "117", " ", "SER",],]
KAW = [ [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "454", " ", "GLY",], [ "456", " ", "GLY",], [ "457", " ", "GLY",],]
KAX = [ [ "10", " ", "VAL",], [ "11", " ", "TYR",], [ "12", " ", "PRO",], [ "13", " ", "ARG",], [ "14", " ", "PRO",], [ "15", " ", "PRO",], [ "19", " ", "TYR",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "31", " ", "ARG",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "35", " ", "GLN",], [ "36", " ", "ASN",], [ "45", " ", "ALA",], [ "46", " ", "SER",], [ "47", " ", "ALA",], [ "48", " ", "ALA",], [ "50", " ", "PRO",], [ "52", " ", "ALA",], [ "53", " ", "SER",],]
KAY = [ [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "356", " ", "ALA",], [ "357", " ", "ALA",], [ "358", " ", "ALA",], [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "361", " ", "SER",], [ "362", " ", "ARG",], [ "467", " ", "GLY",], [ "468", " ", "GLY",], [ "469", " ", "GLY",], [ "470", " ", "GLY",], [ "474", " ", "GLU",], [ "475", " ", "ALA",],]
KAZ = [ [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",],]
KBA = [ [ "20", " ", "ARG",], [ "21", " ", "GLY",], [ "22", " ", "ALA",], [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",],]
KBB = [ [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "431", " ", "ALA",], [ "433", " ", "SER",], [ "434", " ", "SER",],]
KBC = [ [ "368", " ", "PRO",], [ "369", " ", "LEU",], [ "370", " ", "ALA",], [ "371", " ", "LEU",], [ "373", " ", "GLY",],]
KBD = [ [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "402", " ", "ALA",], [ "411", " ", "LEU",],]
KBE = [ [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "398", " ", "ALA",], [ "410", " ", "ASP",], [ "411", " ", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
ARG = 1
CYS = 1
GLU = 1
GLY = 2
ILE = 1
LEU = 1
LYS = 2
MET = 1
PRO = 1
SER = 1
THR = 2
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 8
R2 = 1
R3 = 5
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
CYS = 1
GLU = 1
GLY = 2
LEU = 2
LYS = 1
MET = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 1
GLN = 2
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 2
R2 = 0
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
GLY = 1
LEU = 1
PHE = 1
PRO = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 4
R2 = 1
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ALA = 1
CYS = 1
GLN = 1
GLU = 1
GLY = 1
HIS = 1
LEU = 2
LYS = 2
PRO = 1
SER = 1
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 6
R2 = 0
R3 = 4
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 3
VAL = 2

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
GLY = 1
LEU = 2
PHE = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
ASP = 2
CYS = 1
GLU = 1
ILE = 1
LEU = 2
SER = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 4
R2 = 0
R3 = 2
R4 = 3
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
MET = 1
PRO = 2
SER = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 2
R2 = 2
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
CYS = 3
GLU = 2
GLY = 5
HIS = 1
LEU = 4
LYS = 2
MET = 2
PHE = 1
PRO = 1
THR = 2
TRP = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 13
R2 = 3
R3 = 8
R4 = 2
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ARG = 2
CYS = 2
ILE = 2

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ARG = 3
ASN = 1
CYS = 2
ILE = 1
LYS = 1
THR = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 1
R2 = 0
R3 = 4
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ASP = 1
GLU = 1
GLY = 1
MET = 2
PRO = 1
TRP = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 2
R2 = 1
R3 = 2
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
HIS = 1
ILE = 1
LEU = 1
MET = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ASN = 1
ASP = 1
CYS = 4
ILE = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 1
R2 = 0
R3 = 7
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 2
GLN = 1
GLY = 1
LEU = 1
TYR = 2

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 4
R2 = 2
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ARG = 1
ASN = 1
CYS = 1
GLY = 6
LEU = 2
LYS = 2
PHE = 1
PRO = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 9
R2 = 2
R3 = 4
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ARG = 1
GLN = 1
GLU = 1
LEU = 1
PRO = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ARG = 1
GLN = 2
GLU = 1
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 6
ARG = 1
ASP = 2
CYS = 1
GLN = 3
GLU = 6
GLY = 12
HIS = 1
LEU = 8
LYS = 3
PHE = 2
PRO = 3
SER = 6
THR = 6
TRP = 1
TYR = 3

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 29
R2 = 6
R3 = 16
R4 = 8
R5 = 5
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
ASP = 1
GLU = 2
PHE = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 1
R2 = 2
R3 = 2
R4 = 3
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 2
ARG = 2
ASP = 2
GLN = 25
GLU = 3
GLY = 4
HIS = 1
LEU = 6
PRO = 3
SER = 3
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 16
R2 = 1
R3 = 29
R4 = 5
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
GLY = 3
LEU = 1
PHE = 1
THR = 1

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 5
R2 = 1
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 4
ARG = 2
ASN = 1
GLN = 2
ILE = 1
PHE = 1
PRO = 4
SER = 3
TYR = 2
VAL = 3

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 12
R2 = 3
R3 = 6
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 4
ARG = 1
ASP = 1
GLN = 1
GLU = 1
GLY = 4
LEU = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 9
R2 = 1
R3 = 2
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
GLN = 6
LEU = 2

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 2
R2 = 0
R3 = 6
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
GLN = 2
GLY = 1
LEU = 1
PHE = 2
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 4
R2 = 2
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ALA = 3
LYS = 1
SER = 3

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 3
R2 = 0
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 1
GLY = 1
LEU = 2
PRO = 1

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBD.RESIDUES]
ALA = 3
ASP = 1
GLY = 1
LEU = 2
PRO = 1
SER = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KBD.CLASS]
R1 = 7
R2 = 2
R3 = 1
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBE.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
GLU = 1
LEU = 2
PRO = 1

[RESULTS.FREQUENCY.KBE.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 2
R5 = 0
RX = 0
