# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/28_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_28_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 18.58
KAB = 90.94
KAC = 9.94
KAD = 36.29
KAE = 74.09
KAF = 120.1
KAG = 841.54
KAH = 108.0
KAI = 19.87
KAJ = 17.06
KAK = 253.8
KAL = 238.68
KAM = 327.46
KAN = 82.94
KAO = 12.31
KAP = 173.23
KAQ = 11.23
KAR = 9.29
KAS = 7.78
KAT = 198.29
KAU = 15.34
KAV = 11.23
KAW = 61.56
KAX = 21.38
KAY = 369.58
KAZ = 36.5
KBA = 19.87
KBB = 29.81

[RESULTS.AREA]
KAA = 13.56
KAB = 121.65
KAC = 15.11
KAD = 43.89
KAE = 95.67
KAF = 103.27
KAG = 751.4
KAH = 93.44
KAI = 39.31
KAJ = 21.32
KAK = 213.08
KAL = 193.6
KAM = 216.24
KAN = 103.1
KAO = 20.32
KAP = 145.23
KAQ = 12.12
KAR = 15.79
KAS = 17.13
KAT = 180.05
KAU = 22.21
KAV = 15.65
KAW = 75.46
KAX = 35.82
KAY = 316.96
KAZ = 48.17
KBA = 31.23
KBB = 21.09

[RESULTS.MAX_DEPTH]
KAA = 1.04
KAB = 5.16
KAC = 0.85
KAD = 1.2
KAE = 1.9
KAF = 2.16
KAG = 6.18
KAH = 3.7
KAI = 2.47
KAJ = 0.6
KAK = 3.6
KAL = 2.62
KAM = 2.4
KAN = 1.8
KAO = 1.04
KAP = 3.0
KAQ = 0.6
KAR = 0.6
KAS = 1.2
KAT = 3.84
KAU = 0.85
KAV = 0.6
KAW = 3.0
KAX = 1.2
KAY = 3.06
KAZ = 1.7
KBA = 1.8
KBB = 1.2

[RESULTS.AVG_DEPTH]
KAA = 0.19
KAB = 1.94
KAC = 0.29
KAD = 0.25
KAE = 0.56
KAF = 0.65
KAG = 1.41
KAH = 1.14
KAI = 0.96
KAJ = 0.06
KAK = 1.04
KAL = 0.55
KAM = 0.57
KAN = 0.35
KAO = 0.29
KAP = 0.77
KAQ = 0.02
KAR = 0.1
KAS = 0.4
KAT = 1.55
KAU = 0.17
KAV = 0.12
KAW = 0.77
KAX = 0.36
KAY = 0.81
KAZ = 0.46
KBA = 0.51
KBB = 0.19

[RESULTS.AVG_HYDROPATHY]
KAA = 0.32
KAB = 0.0
KAC = -0.41
KAD = 0.12
KAE = 0.23
KAF = 0.04
KAG = -0.09
KAH = -0.56
KAI = -0.1
KAJ = 0.15
KAK = 0.31
KAL = -0.06
KAM = 0.23
KAN = -0.04
KAO = 0.02
KAP = -0.03
KAQ = 2.23
KAR = -0.72
KAS = 0.98
KAT = -0.54
KAU = 0.85
KAV = 0.84
KAW = 0.84
KAX = 0.72
KAY = 0.66
KAZ = 1.37
KBA = 0.6
KBB = 0.76
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "407", " ", "ARG",], [ "408", " ", "TYR",],]
KAB = [ [ "386", " ", "ARG",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "403", " ", "ALA",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "408", " ", "TYR",], [ "409", " ", "GLY",],]
KAC = [ [ "478", " ", "VAL",], [ "482", " ", "GLY",], [ "483", " ", "TYR",], [ "484", " ", "THR",], [ "485", " ", "ARG",],]
KAD = [ [ "386", " ", "ARG",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "392", " ", "PRO",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",],]
KAE = [ [ "490", " ", "LEU",], [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "608", " ", "ARG",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KAF = [ [ "501", " ", "ASP",], [ "502", " ", "VAL",], [ "503", " ", "TRP",], [ "504", " ", "TYR",], [ "505", " ", "PRO",], [ "506", " ", "GLY",], [ "507", " ", "GLY",], [ "508", " ", "MET",], [ "509", " ", "VAL",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "513", " ", "PRO",],]
KAG = [ [ "490", " ", "LEU",], [ "491", " ", "ALA",], [ "493", " ", "GLN",], [ "531", " ", "TYR",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "561", " ", "LEU",], [ "563", " ", "CYS",], [ "564", " ", "GLY",], [ "565", " ", "ASP",], [ "566", " ", "GLU",], [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "579", " ", "SER",], [ "605", " ", "ASP",], [ "606", " ", "LYS",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "619", " ", "LYS",], [ "622", " ", "GLU",], [ "623", " ", "ALA",], [ "624", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "644", " ", "PRO",],]
KAH = [ [ "588", " ", "ALA",], [ "590", " ", "GLY",], [ "591", " ", "LYS",], [ "594", " ", "TYR",], [ "617", " ", "LEU",], [ "618", " ", "ARG",], [ "620", " ", "CYS",], [ "621", " ", "TYR",], [ "625", " ", "MET",], [ "627", " ", "LEU",],]
KAI = [ [ "583", " ", "PHE",], [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "594", " ", "TYR",], [ "613", " ", "PRO",], [ "617", " ", "LEU",],]
KAJ = [ [ "573", " ", "GLY",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",],]
KAK = [ [ "528", " ", "MET",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "544", " ", "ARG",], [ "545", " ", "ASP",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "552", " ", "TYR",], [ "554", " ", "PHE",], [ "566", " ", "GLU",],]
KAL = [ [ "333", " ", "ALA",], [ "334", " ", "GLY",], [ "335", " ", "SER",], [ "339", " ", "LEU",], [ "340", " ", "GLU",], [ "341", " ", "LEU",], [ "342", " ", "PRO",], [ "343", " ", "SER",], [ "345", " ", "LEU",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "351", " ", "GLY",], [ "352", " ", "ALA",], [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "355", " ", "GLU",], [ "360", " ", "GLN",], [ "361", " ", "SER",], [ "363", " ", "ASP",], [ "364", " ", "TYR",], [ "366", " ", "ASN",], [ "367", " ", "PHE",],]
KAM = [ [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "199", " ", "GLN",], [ "200", " ", "GLU",], [ "201", " ", "ALA",], [ "202", " ", "VAL",], [ "203", " ", "SER",], [ "204", " ", "GLU",], [ "206", " ", "SER",], [ "212", " ", "ARG",], [ "213", " ", "GLU",], [ "214", " ", "ALA",], [ "267", " ", "CYS",], [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",],]
KAN = [ [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "258", " ", "SER",], [ "259", " ", "PRO",], [ "260", " ", "GLY",],]
KAO = [ [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",],]
KAP = [ [ "10", " ", "VAL",], [ "11", " ", "TYR",], [ "162", " ", "SER",], [ "163", " ", "THR",], [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "181", " ", "LEU",], [ "182", " ", "LYS",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "187", " ", "GLU",],]
KAQ = [ [ "32", " ", "GLU",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "41", " ", "HIS",], [ "43", " ", "GLU",],]
KAR = [ [ "49", " ", "PRO",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",],]
KAS = [ [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "36", " ", "ASN",],]
KAT = [ [ "1", " ", "MET",], [ "2", " ", "GLU",], [ "3", " ", "VAL",], [ "4", " ", "GLN",], [ "5", " ", "LEU",], [ "171", " ", "PHE",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "181", " ", "LEU",],]
KAU = [ [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "63", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",],]
KAV = [ [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",],]
KAW = [ [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",],]
KAX = [ [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "86", " ", "GLN",], [ "87", " ", "GLN",],]
KAY = [ [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "88", " ", "GLN",], [ "89", " ", "GLN",], [ "90", " ", "GLN",], [ "91", " ", "GLN",], [ "92", " ", "GLY",], [ "93", " ", "GLU",], [ "94", " ", "ASP",], [ "95", " ", "GLY",], [ "96", " ", "SER",], [ "97", " ", "PRO",], [ "98", " ", "GLN",], [ "115", " ", "GLN",], [ "117", " ", "SER",], [ "118", " ", "GLN",], [ "119", " ", "PRO",], [ "120", " ", "GLN",], [ "122", " ", "ALA",], [ "123", " ", "LEU",], [ "124", " ", "GLU",], [ "125", " ", "CYS",], [ "126", " ", "HIS",], [ "127", " ", "PRO",],]
KAZ = [ [ "98", " ", "GLN",], [ "99", " ", "ALA",], [ "100", " ", "HIS",], [ "101", " ", "ARG",], [ "102", " ", "ARG",], [ "124", " ", "GLU",], [ "125", " ", "CYS",], [ "127", " ", "PRO",],]
KBA = [ [ "89", " ", "GLN",], [ "90", " ", "GLN",], [ "91", " ", "GLN",], [ "116", " ", "PRO",], [ "117", " ", "SER",],]
KBB = [ [ "112", " ", "GLU",], [ "113", " ", "GLU",], [ "114", " ", "GLN",], [ "115", " ", "GLN",], [ "126", " ", "HIS",], [ "132", " ", "VAL",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ARG = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 2
R2 = 2
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 4
ARG = 2
ASP = 1
CYS = 1
GLY = 2
TRP = 1
TYR = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 6
R2 = 3
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ARG = 1
GLY = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 2
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ARG = 1
ASP = 1
GLU = 1
GLY = 1
LEU = 1
PRO = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 3
R2 = 1
R3 = 1
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ARG = 3
ASN = 1
ASP = 1
CYS = 3
ILE = 1
LEU = 2
LYS = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 3
R2 = 1
R3 = 6
R4 = 1
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ARG = 1
ASP = 1
GLY = 2
MET = 1
PRO = 2
SER = 1
TRP = 1
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 7
R2 = 2
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 4
ARG = 1
ASN = 1
ASP = 4
CYS = 3
GLN = 2
GLU = 2
GLY = 5
HIS = 1
ILE = 1
LEU = 5
LYS = 6
MET = 1
PHE = 1
PRO = 4
SER = 2
THR = 2
TYR = 4
VAL = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 20
R2 = 5
R3 = 11
R4 = 6
R5 = 8
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
ARG = 1
CYS = 1
GLY = 1
LEU = 2
LYS = 1
MET = 1
TYR = 2

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 4
R2 = 2
R3 = 2
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 1
ARG = 1
LEU = 1
PHE = 1
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 3
R2 = 2
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ARG = 1
ASN = 1
GLY = 2
PHE = 1
VAL = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 3
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ARG = 2
ASP = 2
GLU = 2
GLY = 2
LEU = 2
MET = 2
PHE = 1
PRO = 1
SER = 1
THR = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 6
R2 = 3
R3 = 4
R4 = 4
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 2
ASN = 1
ASP = 2
GLN = 1
GLU = 2
GLY = 2
LEU = 5
LYS = 1
PHE = 1
PRO = 1
SER = 5
TYR = 2

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 10
R2 = 3
R3 = 7
R4 = 4
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 3
ARG = 1
CYS = 1
GLN = 5
GLU = 3
GLY = 1
LEU = 3
SER = 2
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 8
R2 = 1
R3 = 8
R4 = 3
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 2
CYS = 1
GLU = 2
GLY = 1
HIS = 1
LEU = 2
LYS = 1
PRO = 1
SER = 2
VAL = 3

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 9
R2 = 0
R3 = 3
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
GLU = 1
ILE = 1
LYS = 1
SER = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 1
ASP = 2
GLU = 1
ILE = 1
LEU = 3
LYS = 1
SER = 2
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 6
R2 = 1
R3 = 3
R4 = 3
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ARG = 1
GLU = 2
HIS = 1
PRO = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 1
R2 = 0
R3 = 0
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
LEU = 4
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 5
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ARG = 1
ASN = 1
GLU = 1
ILE = 1
VAL = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 1
ASP = 1
CYS = 1
GLN = 1
GLU = 1
LEU = 3
MET = 1
PHE = 1
SER = 3
VAL = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 5
R2 = 1
R3 = 6
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
GLN = 7

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
GLN = 7

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
GLN = 10
GLU = 1

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 0
R2 = 0
R3 = 10
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
GLN = 5
GLU = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 1
R2 = 0
R3 = 7
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
CYS = 1
GLN = 9
GLU = 2
GLY = 2
HIS = 1
LEU = 1
PRO = 4
SER = 2

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 8
R2 = 0
R3 = 12
R4 = 3
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ALA = 1
ARG = 2
CYS = 1
GLN = 1
GLU = 1
HIS = 1
PRO = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
GLN = 3
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 1
R2 = 0
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
GLN = 2
GLU = 2
HIS = 1
VAL = 1

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 2
R5 = 1
RX = 0
