# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/108_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_108_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 148.61
KAB = 14.69
KAC = 23.98
KAD = 109.73
KAE = 5.18
KAF = 37.15
KAG = 28.3
KAH = 94.39
KAI = 25.27
KAJ = 136.73
KAK = 81.65
KAL = 209.74
KAM = 52.49
KAN = 21.17
KAO = 521.64
KAP = 8.64
KAQ = 25.06
KAR = 15.34
KAS = 164.38
KAT = 9.29
KAU = 9.07
KAV = 80.78
KAW = 476.28
KAX = 6.26
KAY = 47.09
KAZ = 38.45
KBA = 29.38
KBB = 38.02
KBC = 19.87

[RESULTS.AREA]
KAA = 99.83
KAB = 24.07
KAC = 41.54
KAD = 124.11
KAE = 10.33
KAF = 32.33
KAG = 28.1
KAH = 104.66
KAI = 36.55
KAJ = 100.5
KAK = 90.44
KAL = 166.63
KAM = 47.24
KAN = 17.75
KAO = 315.68
KAP = 13.0
KAQ = 34.17
KAR = 20.37
KAS = 153.71
KAT = 10.51
KAU = 13.4
KAV = 110.71
KAW = 393.63
KAX = 13.05
KAY = 64.43
KAZ = 45.82
KBA = 50.35
KBB = 68.53
KBC = 22.22

[RESULTS.MAX_DEPTH]
KAA = 1.7
KAB = 0.85
KAC = 2.24
KAD = 2.62
KAE = 0.6
KAF = 1.2
KAG = 1.2
KAH = 1.8
KAI = 1.2
KAJ = 1.99
KAK = 2.4
KAL = 2.68
KAM = 1.2
KAN = 1.2
KAO = 3.29
KAP = 0.6
KAQ = 1.34
KAR = 0.6
KAS = 2.81
KAT = 0.6
KAU = 0.6
KAV = 3.5
KAW = 3.5
KAX = 0.85
KAY = 1.34
KAZ = 1.8
KBA = 0.0
KBB = 0.0
KBC = 0.85

[RESULTS.AVG_DEPTH]
KAA = 0.44
KAB = 0.15
KAC = 0.91
KAD = 0.73
KAE = 0.12
KAF = 0.28
KAG = 0.26
KAH = 0.6
KAI = 0.29
KAJ = 0.48
KAK = 0.83
KAL = 0.68
KAM = 0.24
KAN = 0.22
KAO = 0.92
KAP = 0.21
KAQ = 0.33
KAR = 0.04
KAS = 0.73
KAT = 0.14
KAU = 0.06
KAV = 0.97
KAW = 1.04
KAX = 0.26
KAY = 0.41
KAZ = 0.59
KBA = 0.0
KBB = 0.0
KBC = 0.11

[RESULTS.AVG_HYDROPATHY]
KAA = -0.55
KAB = -0.43
KAC = 0.61
KAD = 0.18
KAE = -0.41
KAF = 0.2
KAG = -0.18
KAH = 0.25
KAI = -0.11
KAJ = -0.63
KAK = 0.86
KAL = 0.24
KAM = -0.04
KAN = 0.1
KAO = -0.07
KAP = -0.02
KAQ = -0.61
KAR = -0.58
KAS = -0.14
KAT = -0.41
KAU = -0.05
KAV = -0.49
KAW = -0.12
KAX = -0.16
KAY = 0.01
KAZ = -0.26
KBA = 0.81
KBB = -0.59
KBC = -0.45
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "202", " ", "VAL",], [ "203", " ", "SER",], [ "204", " ", "GLU",], [ "205", " ", "GLY",], [ "206", " ", "SER",], [ "207", " ", "SER",], [ "208", " ", "SER",],]
KAB = [ [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "202", " ", "VAL",], [ "203", " ", "SER",],]
KAC = [ [ "176", " ", "SER",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "182", " ", "LYS",], [ "186", " ", "SER",], [ "187", " ", "GLU",],]
KAD = [ [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "170", " ", "THR",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "181", " ", "LEU",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "207", " ", "SER",], [ "208", " ", "SER",], [ "209", " ", "GLY",], [ "210", " ", "ARG",],]
KAE = [ [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "207", " ", "SER",],]
KAF = [ [ "164", " ", "LEU",], [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "210", " ", "ARG",], [ "211", " ", "ALA",], [ "212", " ", "ARG",], [ "213", " ", "GLU",],]
KAG = [ [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "229", " ", "THR",], [ "230", " ", "SER",],]
KAH = [ [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",],]
KAI = [ [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "33", " ", "VAL",],]
KAJ = [ [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",], [ "276", " ", "PRO",], [ "277", " ", "PRO",], [ "279", " ", "VAL",], [ "280", " ", "ARG",], [ "281", " ", "PRO",],]
KAK = [ [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "77", " ", "GLN",],]
KAL = [ [ "112", " ", "GLU",], [ "113", " ", "GLU",], [ "114", " ", "GLN",], [ "115", " ", "GLN",], [ "118", " ", "GLN",], [ "119", " ", "PRO",], [ "120", " ", "GLN",], [ "121", " ", "SER",], [ "122", " ", "ALA",], [ "123", " ", "LEU",], [ "124", " ", "GLU",], [ "125", " ", "CYS",], [ "126", " ", "HIS",], [ "127", " ", "PRO",], [ "128", " ", "GLU",], [ "129", " ", "ARG",], [ "286", " ", "PRO",], [ "287", " ", "LEU",], [ "288", " ", "ALA",], [ "289", " ", "GLU",], [ "290", " ", "CYS",], [ "291", " ", "LYS",], [ "292", " ", "GLY",],]
KAM = [ [ "303", " ", "THR",], [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "306", " ", "THR",], [ "307", " ", "ALA",], [ "308", " ", "GLU",], [ "309", " ", "TYR",], [ "310", " ", "SER",], [ "311", " ", "PRO",], [ "414", " ", "LEU",], [ "415", " ", "HIS",], [ "416", " ", "GLY",], [ "417", " ", "ALA",],]
KAN = [ [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "443", " ", "GLU",], [ "444", " ", "GLY",], [ "445", " ", "GLN",], [ "446", " ", "LEU",],]
KAO = [ [ "316", " ", "TYR",], [ "317", " ", "THR",], [ "318", " ", "LYS",], [ "319", " ", "GLY",], [ "320", " ", "LEU",], [ "321", " ", "GLU",], [ "322", " ", "GLY",], [ "323", " ", "GLU",], [ "324", " ", "SER",], [ "325", " ", "LEU",], [ "326", " ", "GLY",], [ "327", " ", "CYS",], [ "349", " ", "LYS",], [ "351", " ", "GLY",], [ "352", " ", "ALA",], [ "376", " ", "PRO",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "403", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",],]
KAP = [ [ "432", " ", "SER",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",],]
KAQ = [ [ "329", " ", "GLY",], [ "330", " ", "SER",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "353", " ", "LEU",], [ "355", " ", "GLU",], [ "356", " ", "ALA",], [ "357", " ", "ALA",], [ "362", " ", "ARG",],]
KAR = [ [ "341", " ", "LEU",], [ "342", " ", "PRO",], [ "344", " ", "THR",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",],]
KAS = [ [ "469", " ", "GLY",], [ "470", " ", "GLY",], [ "471", " ", "GLY",], [ "472", " ", "GLY",], [ "492", " ", "GLY",], [ "493", " ", "GLN",], [ "494", " ", "GLU",], [ "495", " ", "SER",], [ "496", " ", "ASP",], [ "497", " ", "PHE",], [ "498", " ", "THR",], [ "499", " ", "ALA",], [ "505", " ", "PRO",], [ "506", " ", "GLY",], [ "507", " ", "GLY",], [ "508", " ", "MET",], [ "509", " ", "VAL",], [ "510", " ", "SER",],]
KAT = [ [ "480", " ", "PRO",], [ "481", " ", "TYR",], [ "526", " ", "PRO",], [ "527", " ", "TRP",],]
KAU = [ [ "475", " ", "ALA",], [ "513", " ", "PRO",], [ "515", " ", "PRO",], [ "516", " ", "SER",], [ "517", " ", "PRO",],]
KAV = [ [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "545", " ", "ASP",], [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",],]
KAW = [ [ "541", " ", "GLU",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "561", " ", "LEU",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "571", " ", "HIS",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "632", " ", "ARG",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "642", " ", "THR",], [ "643", " ", "ARG",], [ "644", " ", "PRO",],]
KAX = [ [ "596", " ", "CYS",], [ "597", " ", "ALA",], [ "598", " ", "SER",], [ "602", " ", "CYS",], [ "612", " ", "CYS",], [ "614", " ", "SER",],]
KAY = [ [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "602", " ", "CYS",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "617", " ", "LEU",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KAZ = [ [ "561", " ", "LEU",], [ "562", " ", "ILE",], [ "604", " ", "ILE",], [ "619", " ", "LYS",], [ "622", " ", "GLU",], [ "623", " ", "ALA",], [ "644", " ", "PRO",],]
KBA = [ [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "583", " ", "PHE",], [ "609", " ", "ARG",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "619", " ", "LYS",],]
KBB = [ [ "561", " ", "LEU",], [ "562", " ", "ILE",], [ "571", " ", "HIS",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "576", " ", "THR",], [ "580", " ", "CYS",], [ "584", " ", "PHE",], [ "623", " ", "ALA",], [ "625", " ", "MET",],]
KBC = [ [ "587", " ", "ALA",], [ "588", " ", "ALA",], [ "590", " ", "GLY",], [ "592", " ", "GLN",], [ "593", " ", "LYS",], [ "594", " ", "TYR",], [ "617", " ", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
GLN = 1
GLU = 2
GLY = 1
ILE = 1
LEU = 3
MET = 1
SER = 6
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 0
R3 = 9
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
GLN = 4
LEU = 2
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 3
R2 = 0
R3 = 5
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 1
ASP = 1
GLU = 1
LYS = 1
SER = 3

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLY = 1
ILE = 1
LEU = 4
SER = 3
THR = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 7
R2 = 0
R3 = 4
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ALA = 1
PHE = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 1
R2 = 1
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 1
ARG = 2
GLU = 1
LEU = 2
SER = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ASN = 1
ASP = 1
GLY = 1
LEU = 1
LYS = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 2
R2 = 1
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 2
ASN = 1
ASP = 1
CYS = 1
GLU = 2
GLY = 1
LEU = 1
LYS = 2
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 6
R2 = 0
R3 = 3
R4 = 3
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ASN = 1
GLN = 2
LEU = 1
PHE = 2
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 3
R2 = 2
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 1
ARG = 2
ASP = 1
GLY = 2
LEU = 3
MET = 1
PRO = 4
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 11
R2 = 1
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
GLN = 12

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 0
R2 = 0
R3 = 12
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 2
ARG = 1
CYS = 2
GLN = 4
GLU = 5
GLY = 1
HIS = 1
LEU = 2
LYS = 1
PRO = 3
SER = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 8
R2 = 0
R3 = 7
R4 = 5
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 2
ASP = 1
GLU = 2
GLY = 1
HIS = 1
LEU = 1
PRO = 1
SER = 1
THR = 2
TYR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 5
R2 = 1
R3 = 3
R4 = 3
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
GLN = 1
GLU = 1
GLY = 1
LEU = 1
THR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 6
CYS = 1
GLN = 1
GLU = 2
GLY = 5
LEU = 2
LYS = 2
PRO = 1
SER = 2
THR = 1
TRP = 1
TYR = 2

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 14
R2 = 3
R3 = 5
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
HIS = 1
LEU = 1
PHE = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 1
R2 = 1
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ALA = 2
ARG = 1
GLU = 1
GLY = 1
LEU = 2
LYS = 1
SER = 3

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 5
R2 = 0
R3 = 3
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
LEU = 2
PRO = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 1
ASP = 1
GLN = 1
GLU = 1
GLY = 7
MET = 1
PHE = 1
PRO = 1
SER = 2
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 10
R2 = 1
R3 = 5
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
PRO = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 2
R2 = 2
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
PRO = 3
SER = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ASP = 2
GLU = 1
HIS = 1
ILE = 1
LEU = 1
SER = 1
THR = 1
TYR = 3
VAL = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 3
R2 = 3
R3 = 2
R4 = 3
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
ARG = 2
ASN = 1
ASP = 1
CYS = 3
GLN = 1
GLU = 1
GLY = 3
HIS = 2
LEU = 3
LYS = 2
PHE = 1
PRO = 3
THR = 2
TYR = 2

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 10
R2 = 3
R3 = 7
R4 = 2
R5 = 6
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 1
CYS = 3
SER = 2

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 1
R2 = 0
R3 = 5
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ARG = 1
ASN = 1
CYS = 3
LEU = 2
LYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 2
R2 = 1
R3 = 5
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ALA = 1
GLU = 1
ILE = 2
LEU = 1
LYS = 1
PRO = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ARG = 2
CYS = 2
ILE = 1
LYS = 1
PHE = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 1
R2 = 1
R3 = 2
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ALA = 2
CYS = 1
GLY = 1
HIS = 1
ILE = 1
LEU = 2
MET = 1
PHE = 1
THR = 1

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 6
R2 = 1
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 2
GLN = 1
GLY = 1
LEU = 1
LYS = 1
TYR = 1

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0
