# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/4_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_4_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 143.42
KAB = 386.21
KAC = 141.26
KAD = 202.39
KAE = 132.19
KAF = 18.79
KAG = 481.46
KAH = 8.42
KAI = 2020.68
KAJ = 127.01
KAK = 104.54
KAL = 13.39
KAM = 236.3
KAN = 27.22
KAO = 7.56
KAP = 12.96
KAQ = 21.38
KAR = 15.77
KAS = 300.02
KAT = 70.63
KAU = 101.3

[RESULTS.AREA]
KAA = 113.73
KAB = 344.36
KAC = 147.05
KAD = 151.88
KAE = 121.72
KAF = 15.91
KAG = 516.08
KAH = 19.85
KAI = 1323.91
KAJ = 140.76
KAK = 101.89
KAL = 12.28
KAM = 218.38
KAN = 37.23
KAO = 11.94
KAP = 19.79
KAQ = 23.02
KAR = 12.76
KAS = 266.78
KAT = 72.52
KAU = 96.01

[RESULTS.MAX_DEPTH]
KAA = 1.99
KAB = 4.69
KAC = 4.41
KAD = 2.47
KAE = 2.24
KAF = 0.6
KAG = 5.94
KAH = 1.2
KAI = 6.41
KAJ = 2.4
KAK = 1.8
KAL = 0.6
KAM = 6.6
KAN = 2.4
KAO = 0.6
KAP = 0.6
KAQ = 0.85
KAR = 0.6
KAS = 3.5
KAT = 2.47
KAU = 1.8

[RESULTS.AVG_DEPTH]
KAA = 0.62
KAB = 1.28
KAC = 0.99
KAD = 0.76
KAE = 0.5
KAF = 0.04
KAG = 1.48
KAH = 0.48
KAI = 1.57
KAJ = 0.78
KAK = 0.54
KAL = 0.02
KAM = 2.85
KAN = 0.7
KAO = 0.09
KAP = 0.2
KAQ = 0.17
KAR = 0.11
KAS = 0.95
KAT = 0.63
KAU = 0.44

[RESULTS.AVG_HYDROPATHY]
KAA = 0.2
KAB = -0.05
KAC = 0.62
KAD = -0.13
KAE = -0.56
KAF = -0.61
KAG = -0.02
KAH = -0.03
KAI = -0.06
KAJ = -0.01
KAK = 0.19
KAL = 0.64
KAM = -0.31
KAN = -0.03
KAO = 0.3
KAP = -1.11
KAQ = 0.65
KAR = -0.64
KAS = 0.78
KAT = 0.36
KAU = 0.14
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "301", " ", "LYS",], [ "302", " ", "SER",], [ "303", " ", "THR",], [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "306", " ", "THR",], [ "307", " ", "ALA",], [ "309", " ", "TYR",], [ "325", " ", "LEU",], [ "326", " ", "GLY",], [ "327", " ", "CYS",], [ "328", " ", "SER",], [ "330", " ", "SER",], [ "331", " ", "ALA",],]
KAB = [ [ "336", " ", "SER",], [ "337", " ", "GLY",], [ "338", " ", "THR",], [ "339", " ", "LEU",], [ "340", " ", "GLU",], [ "341", " ", "LEU",], [ "342", " ", "PRO",], [ "343", " ", "SER",], [ "344", " ", "THR",], [ "345", " ", "LEU",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "351", " ", "GLY",], [ "352", " ", "ALA",], [ "360", " ", "GLN",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "402", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",],]
KAC = [ [ "344", " ", "THR",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "356", " ", "ALA",], [ "358", " ", "ALA",], [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "361", " ", "SER",], [ "362", " ", "ARG",], [ "363", " ", "ASP",], [ "364", " ", "TYR",], [ "365", " ", "TYR",], [ "366", " ", "ASN",], [ "367", " ", "PHE",], [ "368", " ", "PRO",], [ "369", " ", "LEU",],]
KAD = [ [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "258", " ", "SER",], [ "259", " ", "PRO",], [ "260", " ", "GLY",], [ "261", " ", "GLU",], [ "262", " ", "GLN",], [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",],]
KAE = [ [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "387", " ", "ILE",], [ "389", " ", "LEU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "402", " ", "ALA",],]
KAF = [ [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "274", " ", "GLY",], [ "275", " ", "VAL",], [ "356", " ", "ALA",], [ "357", " ", "ALA",],]
KAG = [ [ "480", " ", "PRO",], [ "483", " ", "TYR",], [ "484", " ", "THR",], [ "485", " ", "ARG",], [ "486", " ", "PRO",], [ "487", " ", "PRO",], [ "488", " ", "GLN",], [ "489", " ", "GLY",], [ "490", " ", "LEU",], [ "491", " ", "ALA",], [ "492", " ", "GLY",], [ "495", " ", "SER",], [ "496", " ", "ASP",], [ "497", " ", "PHE",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "543", " ", "ALA",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAH = [ [ "239", " ", "LEU",], [ "244", " ", "SER",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "256", " ", "HIS",],]
KAI = [ [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "199", " ", "GLN",], [ "200", " ", "GLU",], [ "201", " ", "ALA",], [ "202", " ", "VAL",], [ "203", " ", "SER",], [ "204", " ", "GLU",], [ "207", " ", "SER",], [ "208", " ", "SER",], [ "209", " ", "GLY",], [ "210", " ", "ARG",], [ "211", " ", "ALA",], [ "213", " ", "GLU",], [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "228", " ", "GLY",], [ "229", " ", "THR",], [ "230", " ", "SER",], [ "232", " ", "ILE",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "246", " ", "SER",], [ "247", " ", "MET",], [ "248", " ", "GLY",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "377", " ", "PRO",], [ "378", " ", "PRO",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "395", " ", "TYR",], [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "431", " ", "ALA",],]
KAJ = [ [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "624", " ", "GLY",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",],]
KAK = [ [ "518", " ", "THR",], [ "519", " ", "CYS",], [ "520", " ", "VAL",], [ "521", " ", "LYS",], [ "522", " ", "SER",], [ "523", " ", "GLU",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "531", " ", "TYR",],]
KAL = [ [ "509", " ", "VAL",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "513", " ", "PRO",], [ "514", " ", "TYR",], [ "526", " ", "PRO",],]
KAM = [ [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "575", " ", "LEU",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAN = [ [ "597", " ", "ALA",], [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "611", " ", "ASN",], [ "614", " ", "SER",], [ "615", " ", "CYS",],]
KAO = [ [ "176", " ", "SER",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "182", " ", "LYS",],]
KAP = [ [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "169", " ", "PRO",], [ "438", " ", "LEU",], [ "439", " ", "PHE",],]
KAQ = [ [ "84", " ", "PRO",], [ "87", " ", "GLN",], [ "88", " ", "GLN",], [ "91", " ", "GLN",], [ "92", " ", "GLY",], [ "94", " ", "ASP",], [ "95", " ", "GLY",], [ "96", " ", "SER",], [ "97", " ", "PRO",],]
KAR = [ [ "107", " ", "TYR",], [ "108", " ", "LEU",], [ "109", " ", "VAL",], [ "110", " ", "LEU",], [ "111", " ", "ASP",], [ "112", " ", "GLU",], [ "113", " ", "GLU",],]
KAS = [ [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "87", " ", "GLN",], [ "88", " ", "GLN",], [ "89", " ", "GLN",], [ "92", " ", "GLY",], [ "101", " ", "ARG",],]
KAT = [ [ "54", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",],]
KAU = [ [ "1", " ", "MET",], [ "8", " ", "GLY",], [ "9", " ", "ARG",], [ "10", " ", "VAL",], [ "11", " ", "TYR",], [ "12", " ", "PRO",], [ "13", " ", "ARG",], [ "14", " ", "PRO",], [ "16", " ", "SER",], [ "17", " ", "LYS",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 2
ASP = 1
CYS = 1
GLU = 1
GLY = 1
LEU = 1
LYS = 1
SER = 3
THR = 2
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 4
R2 = 1
R3 = 6
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 5
ARG = 1
CYS = 1
GLN = 2
GLU = 1
GLY = 2
LEU = 4
LYS = 1
PRO = 1
SER = 4
THR = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 12
R2 = 2
R3 = 9
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ASP = 2
GLN = 1
LEU = 3
LYS = 1
PHE = 1
PRO = 1
SER = 1
THR = 1
TYR = 4

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 6
R2 = 5
R3 = 4
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ARG = 1
GLN = 1
GLU = 2
GLY = 2
HIS = 1
LEU = 4
PRO = 2
SER = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 9
R2 = 0
R3 = 2
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ALA = 4
ASN = 1
ASP = 1
GLY = 1
ILE = 1
LEU = 2
MET = 1
PRO = 1
SER = 1
TRP = 1
TYR = 2

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 9
R2 = 3
R3 = 3
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 2
GLY = 1
LEU = 1
PRO = 1
VAL = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 6
R2 = 0
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 2
ARG = 3
ASP = 3
GLN = 1
GLU = 1
GLY = 4
HIS = 1
ILE = 1
LEU = 3
LYS = 2
MET = 2
PHE = 1
PRO = 4
SER = 2
THR = 3
TYR = 5

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 14
R2 = 6
R3 = 8
R4 = 4
R5 = 6
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
GLU = 1
HIS = 1
LEU = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 9
ARG = 1
ASN = 3
ASP = 3
CYS = 2
GLN = 4
GLU = 8
GLY = 6
HIS = 1
ILE = 2
LEU = 9
LYS = 4
MET = 2
PRO = 3
SER = 12
THR = 2
TYR = 2
VAL = 4

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 33
R2 = 2
R3 = 25
R4 = 11
R5 = 6
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 2
GLY = 4
HIS = 1
LYS = 1
MET = 1
PHE = 1
THR = 1
VAL = 2

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 7
R2 = 1
R3 = 5
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ASP = 1
CYS = 1
GLU = 1
GLY = 1
LYS = 1
MET = 2
PRO = 1
SER = 1
THR = 1
TRP = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 3
R2 = 2
R3 = 5
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ARG = 1
PRO = 2
SER = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 1
ARG = 1
GLN = 1
GLY = 1
HIS = 1
ILE = 1
LEU = 3
LYS = 2
PRO = 3
SER = 1
THR = 2

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 9
R2 = 0
R3 = 4
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ASP = 1
CYS = 2
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 1
R2 = 0
R3 = 6
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
ASP = 1
CYS = 1
LYS = 1
SER = 2

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
LEU = 3
PHE = 1
PRO = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 4
R2 = 1
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ASP = 1
GLN = 3
GLY = 2
PRO = 2
SER = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 4
R2 = 0
R3 = 4
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ASP = 1
GLU = 2
LEU = 2
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 3
R2 = 1
R3 = 0
R4 = 3
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ARG = 2
GLN = 18
GLU = 1
GLY = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 2
R2 = 0
R3 = 20
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
GLN = 8
LEU = 3

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 3
R2 = 0
R3 = 8
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ARG = 2
ASN = 1
GLN = 1
GLY = 1
LEU = 1
LYS = 1
MET = 1
PRO = 2
SER = 1
THR = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 5
R2 = 2
R3 = 5
R4 = 0
R5 = 3
RX = 0
