# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/114_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_114_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 58.32
KAB = 32.4
KAC = 49.03
KAD = 13.61
KAE = 49.03
KAF = 7.56
KAG = 9.29
KAH = 10.15
KAI = 704.38
KAJ = 843.26
KAK = 36.72
KAL = 8.42
KAM = 237.6
KAN = 112.54
KAO = 107.78
KAP = 12.1
KAQ = 376.27
KAR = 69.12
KAS = 85.32
KAT = 11.23
KAU = 7.78
KAV = 11.66
KAW = 55.94
KAX = 65.66
KAY = 17.28
KAZ = 8.42
KBA = 24.41

[RESULTS.AREA]
KAA = 79.74
KAB = 43.76
KAC = 60.42
KAD = 15.83
KAE = 48.61
KAF = 14.49
KAG = 14.75
KAH = 19.42
KAI = 508.13
KAJ = 485.27
KAK = 39.89
KAL = 10.11
KAM = 223.1
KAN = 119.04
KAO = 97.4
KAP = 23.49
KAQ = 299.66
KAR = 86.19
KAS = 130.82
KAT = 26.42
KAU = 15.87
KAV = 21.37
KAW = 65.06
KAX = 83.86
KAY = 38.91
KAZ = 19.7
KBA = 31.76

[RESULTS.MAX_DEPTH]
KAA = 3.29
KAB = 2.16
KAC = 1.8
KAD = 0.6
KAE = 1.7
KAF = 0.6
KAG = 1.34
KAH = 0.85
KAI = 4.33
KAJ = 3.65
KAK = 0.85
KAL = 0.6
KAM = 3.0
KAN = 3.06
KAO = 2.08
KAP = 0.6
KAQ = 3.55
KAR = 3.6
KAS = 7.52
KAT = 1.8
KAU = 1.2
KAV = 1.2
KAW = 1.8
KAX = 5.53
KAY = 0.0
KAZ = 1.2
KBA = 0.85

[RESULTS.AVG_DEPTH]
KAA = 1.3
KAB = 0.51
KAC = 0.49
KAD = 0.1
KAE = 0.55
KAF = 0.22
KAG = 0.37
KAH = 0.23
KAI = 1.32
KAJ = 0.93
KAK = 0.14
KAL = 0.06
KAM = 0.76
KAN = 0.54
KAO = 0.52
KAP = 0.1
KAQ = 1.37
KAR = 1.33
KAS = 3.95
KAT = 0.94
KAU = 0.36
KAV = 0.37
KAW = 0.46
KAX = 2.71
KAY = 0.0
KAZ = 0.48
KBA = 0.17

[RESULTS.AVG_HYDROPATHY]
KAA = -0.63
KAB = -0.87
KAC = 0.78
KAD = 0.36
KAE = 0.86
KAF = 0.12
KAG = 0.13
KAH = 0.54
KAI = 0.19
KAJ = -0.02
KAK = 0.16
KAL = -0.32
KAM = 0.11
KAN = -0.28
KAO = 0.45
KAP = -0.47
KAQ = -0.21
KAR = 0.65
KAS = 0.49
KAT = 0.32
KAU = -0.26
KAV = 0.61
KAW = 0.06
KAX = -0.37
KAY = -0.94
KAZ = 0.13
KBA = -0.31
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "172", " ", "PRO",], [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "180", " ", "ASP",], [ "181", " ", "LEU",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "185", " ", "LEU",],]
KAB = [ [ "174", " ", "LEU",], [ "177", " ", "CYS",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",],]
KAC = [ [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",],]
KAD = [ [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "200", " ", "GLU",], [ "201", " ", "ALA",], [ "202", " ", "VAL",],]
KAE = [ [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",],]
KAF = [ [ "5", " ", "LEU",], [ "6", " ", "GLY",], [ "31", " ", "ARG",], [ "36", " ", "ASN",],]
KAG = [ [ "11", " ", "TYR",], [ "16", " ", "SER",], [ "17", " ", "LYS",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "24", " ", "GLN",],]
KAH = [ [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "61", " ", "GLN",], [ "63", " ", "GLN",],]
KAI = [ [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "228", " ", "GLY",], [ "229", " ", "THR",], [ "230", " ", "SER",], [ "231", " ", "THR",], [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "246", " ", "SER",], [ "251", " ", "VAL",], [ "254", " ", "LEU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "258", " ", "SER",], [ "259", " ", "PRO",], [ "260", " ", "GLY",], [ "261", " ", "GLU",], [ "262", " ", "GLN",], [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "267", " ", "CYS",], [ "268", " ", "MET",],]
KAJ = [ [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "275", " ", "VAL",], [ "276", " ", "PRO",], [ "277", " ", "PRO",], [ "279", " ", "VAL",], [ "280", " ", "ARG",], [ "281", " ", "PRO",], [ "293", " ", "SER",], [ "294", " ", "LEU",], [ "295", " ", "LEU",], [ "296", " ", "ASP",], [ "297", " ", "ASP",], [ "298", " ", "SER",], [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "306", " ", "THR",], [ "307", " ", "ALA",], [ "308", " ", "GLU",], [ "309", " ", "TYR",], [ "310", " ", "SER",], [ "311", " ", "PRO",], [ "312", " ", "PHE",], [ "313", " ", "LYS",], [ "314", " ", "GLY",], [ "315", " ", "GLY",], [ "316", " ", "TYR",], [ "317", " ", "THR",], [ "318", " ", "LYS",], [ "319", " ", "GLY",], [ "320", " ", "LEU",], [ "321", " ", "GLU",], [ "322", " ", "GLY",], [ "323", " ", "GLU",],]
KAK = [ [ "343", " ", "SER",], [ "344", " ", "THR",], [ "345", " ", "LEU",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "350", " ", "SER",], [ "351", " ", "GLY",], [ "352", " ", "ALA",], [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "355", " ", "GLU",],]
KAL = [ [ "475", " ", "ALA",], [ "476", " ", "GLY",], [ "477", " ", "ALA",], [ "479", " ", "ALA",], [ "483", " ", "TYR",], [ "484", " ", "THR",],]
KAM = [ [ "380", " ", "PRO",], [ "381", " ", "PRO",], [ "382", " ", "HIS",], [ "383", " ", "PRO",], [ "384", " ", "HIS",], [ "385", " ", "ALA",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "400", " ", "ALA",], [ "402", " ", "ALA",], [ "403", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "407", " ", "ARG",], [ "412", " ", "ALA",],]
KAN = [ [ "371", " ", "LEU",], [ "372", " ", "ALA",], [ "374", " ", "PRO",], [ "375", " ", "PRO",], [ "376", " ", "PRO",], [ "426", " ", "SER",], [ "427", " ", "PRO",], [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "434", " ", "SER",], [ "435", " ", "TRP",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "440", " ", "THR",], [ "441", " ", "ALA",],]
KAO = [ [ "380", " ", "PRO",], [ "381", " ", "PRO",], [ "382", " ", "HIS",], [ "407", " ", "ARG",], [ "408", " ", "TYR",], [ "409", " ", "GLY",], [ "410", " ", "ASP",], [ "411", " ", "LEU",], [ "412", " ", "ALA",], [ "413", " ", "SER",], [ "414", " ", "LEU",], [ "416", " ", "GLY",], [ "417", " ", "ALA",], [ "419", " ", "ALA",],]
KAP = [ [ "380", " ", "PRO",], [ "382", " ", "HIS",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "412", " ", "ALA",], [ "413", " ", "SER",],]
KAQ = [ [ "520", " ", "VAL",], [ "521", " ", "LYS",], [ "522", " ", "SER",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",],]
KAR = [ [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "592", " ", "GLN",], [ "593", " ", "LYS",], [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "613", " ", "PRO",], [ "614", " ", "SER",], [ "616", " ", "ARG",], [ "617", " ", "LEU",],]
KAS = [ [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "579", " ", "SER",], [ "580", " ", "CYS",], [ "583", " ", "PHE",], [ "604", " ", "ILE",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "613", " ", "PRO",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "619", " ", "LYS",],]
KAT = [ [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "608", " ", "ARG",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "615", " ", "CYS",],]
KAU = [ [ "587", " ", "ALA",], [ "590", " ", "GLY",], [ "591", " ", "LYS",], [ "592", " ", "GLN",], [ "594", " ", "TYR",], [ "617", " ", "LEU",], [ "621", " ", "TYR",],]
KAV = [ [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "614", " ", "SER",], [ "617", " ", "LEU",], [ "618", " ", "ARG",],]
KAW = [ [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "567", " ", "ALA",], [ "641", " ", "MET",],]
KAX = [ [ "557", " ", "GLN",], [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "575", " ", "LEU",], [ "635", " ", "ASN",], [ "639", " ", "LEU",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "643", " ", "ARG",], [ "644", " ", "PRO",],]
KAY = [ [ "561", " ", "LEU",], [ "562", " ", "ILE",], [ "571", " ", "HIS",], [ "574", " ", "ALA",], [ "576", " ", "THR",], [ "584", " ", "PHE",], [ "625", " ", "MET",],]
KAZ = [ [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "604", " ", "ILE",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "617", " ", "LEU",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KBA = [ [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "624", " ", "GLY",], [ "626", " ", "THR",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ASP = 2
CYS = 1
GLY = 1
ILE = 1
LEU = 3
PHE = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 7
R2 = 1
R3 = 3
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
CYS = 1
GLN = 1
ILE = 1
LEU = 2
MET = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 4
R2 = 0
R3 = 5
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
GLN = 7
GLU = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 1
R2 = 0
R3 = 9
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
GLN = 4
GLU = 1
LEU = 1
VAL = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 3
R2 = 0
R3 = 4
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
GLN = 9

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 0
R2 = 0
R3 = 9
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ARG = 1
ASN = 1
GLY = 1
LEU = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
GLN = 1
LYS = 1
SER = 1
THR = 1
TYR = 2

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 0
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
GLN = 4
LEU = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 1
R2 = 0
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
ASP = 2
CYS = 2
GLN = 1
GLU = 1
GLY = 4
HIS = 1
ILE = 1
LEU = 4
LYS = 2
MET = 1
PRO = 1
SER = 5
THR = 2
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 14
R2 = 1
R3 = 12
R4 = 3
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 2
ARG = 1
ASP = 3
GLU = 4
GLY = 4
LEU = 5
LYS = 2
PHE = 1
PRO = 5
SER = 3
THR = 2
TYR = 3
VAL = 2

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 18
R2 = 4
R3 = 5
R4 = 7
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ALA = 1
ASP = 1
GLU = 1
GLY = 1
LEU = 3
LYS = 1
SER = 2
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 5
R2 = 1
R3 = 3
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 3
GLY = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 7
ARG = 2
ASN = 1
ASP = 1
GLN = 1
GLU = 1
GLY = 1
HIS = 2
ILE = 1
LEU = 1
PRO = 3
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 13
R2 = 1
R3 = 3
R4 = 2
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 4
HIS = 1
LEU = 1
PRO = 4
SER = 3
THR = 2
TRP = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 9
R2 = 1
R3 = 5
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 3
ARG = 1
ASP = 1
GLY = 2
HIS = 1
LEU = 2
PRO = 2
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 9
R2 = 1
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 3
HIS = 1
PRO = 1
SER = 2
TRP = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ARG = 1
ASP = 1
GLU = 1
GLY = 3
LEU = 1
LYS = 1
MET = 3
PRO = 2
SER = 3
THR = 1
TRP = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 7
R2 = 3
R3 = 7
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ALA = 1
ARG = 2
GLN = 1
LEU = 2
LYS = 1
PRO = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ARG = 2
ASN = 1
CYS = 4
ILE = 2
LYS = 2
PHE = 1
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 3
R2 = 1
R3 = 6
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ARG = 1
ASN = 1
CYS = 3
THR = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 0
R2 = 0
R3 = 5
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
GLN = 1
GLY = 1
LEU = 1
LYS = 1
TYR = 2

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 3
R2 = 2
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ARG = 1
ASN = 1
CYS = 1
LEU = 2
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 2
R2 = 1
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
ASP = 1
GLN = 1
ILE = 1
LYS = 1
MET = 1
PHE = 1
PRO = 2

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
GLN = 1
GLY = 1
LEU = 2
MET = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 5
R2 = 0
R3 = 5
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 1
HIS = 1
ILE = 1
LEU = 1
MET = 1
PHE = 1
THR = 1

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ARG = 1
ASN = 1
ASP = 1
CYS = 2
ILE = 1
LEU = 1
LYS = 1
SER = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 1
GLY = 3
PHE = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 5
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0
