# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/42_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_42_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 22.46
KAB = 1160.14
KAC = 5.62
KAD = 29.59
KAE = 62.86
KAF = 60.26
KAG = 13.39
KAH = 61.78
KAI = 27.86
KAJ = 31.97
KAK = 16.85
KAL = 83.81
KAM = 10.15
KAN = 17.28
KAO = 10.8
KAP = 35.64
KAQ = 263.95
KAR = 35.64
KAS = 30.46
KAT = 8.86
KAU = 21.6
KAV = 11.88
KAW = 54.65
KAX = 7.78
KAY = 34.13
KAZ = 55.73
KBA = 12.96
KBB = 56.81
KBC = 29.16
KBD = 81.22
KBE = 9.5

[RESULTS.AREA]
KAA = 35.64
KAB = 908.39
KAC = 12.01
KAD = 25.08
KAE = 89.62
KAF = 81.82
KAG = 22.3
KAH = 78.69
KAI = 47.68
KAJ = 32.94
KAK = 15.02
KAL = 78.1
KAM = 19.42
KAN = 23.51
KAO = 15.69
KAP = 45.7
KAQ = 216.96
KAR = 33.36
KAS = 40.99
KAT = 17.25
KAU = 23.99
KAV = 22.58
KAW = 50.95
KAX = 8.96
KAY = 45.58
KAZ = 72.85
KBA = 12.9
KBB = 68.02
KBC = 31.76
KBD = 66.47
KBE = 16.03

[RESULTS.MAX_DEPTH]
KAA = 1.8
KAB = 5.82
KAC = 0.6
KAD = 1.34
KAE = 5.4
KAF = 3.06
KAG = 1.7
KAH = 2.16
KAI = 3.06
KAJ = 1.9
KAK = 0.85
KAL = 2.55
KAM = 1.34
KAN = 0.85
KAO = 0.6
KAP = 2.16
KAQ = 4.61
KAR = 1.34
KAS = 0.85
KAT = 1.04
KAU = 0.6
KAV = 1.34
KAW = 1.7
KAX = 0.6
KAY = 1.47
KAZ = 1.34
KBA = 0.6
KBB = 2.24
KBC = 0.85
KBD = 2.16
KBE = 1.2

[RESULTS.AVG_DEPTH]
KAA = 0.44
KAB = 1.62
KAC = 0.18
KAD = 0.31
KAE = 2.43
KAF = 0.83
KAG = 0.53
KAH = 0.55
KAI = 1.64
KAJ = 0.39
KAK = 0.19
KAL = 0.67
KAM = 0.43
KAN = 0.13
KAO = 0.1
KAP = 0.6
KAQ = 1.25
KAR = 0.35
KAS = 0.21
KAT = 0.4
KAU = 0.13
KAV = 0.53
KAW = 0.4
KAX = 0.12
KAY = 0.42
KAZ = 0.32
KBA = 0.13
KBB = 0.67
KBC = 0.13
KBD = 0.42
KBE = 0.2

[RESULTS.AVG_HYDROPATHY]
KAA = 0.29
KAB = 0.32
KAC = -0.41
KAD = 0.92
KAE = 0.95
KAF = 0.16
KAG = -0.29
KAH = 0.14
KAI = -0.77
KAJ = -0.27
KAK = 0.26
KAL = 0.95
KAM = -0.09
KAN = -0.78
KAO = 0.5
KAP = 0.86
KAQ = 0.6
KAR = -0.47
KAS = -0.07
KAT = 0.87
KAU = 1.55
KAV = 0.03
KAW = -0.85
KAX = 0.2
KAY = 0.52
KAZ = 0.15
KBA = -0.64
KBB = -0.19
KBC = 0.15
KBD = -0.09
KBE = -0.26
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "503", " ", "TRP",], [ "504", " ", "TYR",], [ "505", " ", "PRO",], [ "506", " ", "GLY",], [ "507", " ", "GLY",], [ "509", " ", "VAL",], [ "511", " ", "ARG",], [ "513", " ", "PRO",],]
KAB = [ [ "519", " ", "CYS",], [ "520", " ", "VAL",], [ "521", " ", "LYS",], [ "522", " ", "SER",], [ "523", " ", "GLU",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "543", " ", "ALA",], [ "544", " ", "ARG",], [ "546", " ", "HIS",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "558", " ", "LYS",], [ "570", " ", "CYS",], [ "571", " ", "HIS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "624", " ", "GLY",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "628", " ", "GLY",], [ "631", " ", "PHE",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAC = [ [ "516", " ", "SER",], [ "517", " ", "PRO",], [ "519", " ", "CYS",], [ "520", " ", "VAL",], [ "550", " ", "ILE",], [ "552", " ", "TYR",],]
KAD = [ [ "477", " ", "ALA",], [ "478", " ", "VAL",], [ "479", " ", "ALA",], [ "481", " ", "TYR",], [ "482", " ", "GLY",], [ "484", " ", "THR",], [ "485", " ", "ARG",],]
KAE = [ [ "563", " ", "CYS",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "608", " ", "ARG",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "619", " ", "LYS",],]
KAF = [ [ "594", " ", "TYR",], [ "595", " ", "LEU",], [ "596", " ", "CYS",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "604", " ", "ILE",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",],]
KAG = [ [ "596", " ", "CYS",], [ "597", " ", "ALA",], [ "598", " ", "SER",], [ "602", " ", "CYS",], [ "612", " ", "CYS",], [ "614", " ", "SER",], [ "615", " ", "CYS",],]
KAH = [ [ "582", " ", "VAL",], [ "583", " ", "PHE",], [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "592", " ", "GLN",], [ "593", " ", "LYS",], [ "594", " ", "TYR",], [ "613", " ", "PRO",], [ "616", " ", "ARG",], [ "617", " ", "LEU",],]
KAI = [ [ "584", " ", "PHE",], [ "587", " ", "ALA",], [ "588", " ", "ALA",], [ "617", " ", "LEU",], [ "620", " ", "CYS",], [ "621", " ", "TYR",], [ "625", " ", "MET",],]
KAJ = [ [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "431", " ", "ALA",], [ "433", " ", "SER",], [ "434", " ", "SER",], [ "435", " ", "TRP",], [ "437", " ", "THR",], [ "438", " ", "LEU",],]
KAK = [ [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",],]
KAL = [ [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "87", " ", "GLN",],]
KAM = [ [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "199", " ", "GLN",], [ "200", " ", "GLU",],]
KAN = [ [ "425", " ", "GLY",], [ "426", " ", "SER",], [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "442", " ", "GLU",], [ "443", " ", "GLU",], [ "444", " ", "GLY",],]
KAO = [ [ "217", " ", "ALA",], [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",],]
KAP = [ [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",],]
KAQ = [ [ "385", " ", "ALA",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "402", " ", "ALA",], [ "403", " ", "ALA",], [ "405", " ", "GLN",], [ "407", " ", "ARG",], [ "414", " ", "LEU",],]
KAR = [ [ "341", " ", "LEU",], [ "344", " ", "THR",], [ "345", " ", "LEU",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",],]
KAS = [ [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",],]
KAT = [ [ "102", " ", "ARG",], [ "104", " ", "PRO",], [ "105", " ", "THR",], [ "110", " ", "LEU",], [ "111", " ", "ASP",], [ "112", " ", "GLU",],]
KAU = [ [ "407", " ", "ARG",], [ "410", " ", "ASP",], [ "412", " ", "ALA",], [ "414", " ", "LEU",], [ "415", " ", "HIS",],]
KAV = [ [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",],]
KAW = [ [ "45", " ", "ALA",], [ "48", " ", "ALA",], [ "49", " ", "PRO",], [ "50", " ", "PRO",], [ "51", " ", "GLY",], [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",],]
KAX = [ [ "54", " ", "LEU",], [ "59", " ", "GLN",], [ "60", " ", "GLN",],]
KAY = [ [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "361", " ", "SER",], [ "362", " ", "ARG",], [ "363", " ", "ASP",], [ "364", " ", "TYR",], [ "366", " ", "ASN",], [ "367", " ", "PHE",],]
KAZ = [ [ "241", " ", "LYS",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "258", " ", "SER",], [ "261", " ", "GLU",], [ "262", " ", "GLN",], [ "263", " ", "LEU",], [ "264", " ", "ARG",],]
KBA = [ [ "366", " ", "ASN",], [ "367", " ", "PHE",], [ "368", " ", "PRO",], [ "369", " ", "LEU",], [ "370", " ", "ALA",], [ "371", " ", "LEU",],]
KBB = [ [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "35", " ", "GLN",],]
KBC = [ [ "32", " ", "GLU",], [ "34", " ", "ILE",], [ "36", " ", "ASN",], [ "37", " ", "PRO",], [ "38", " ", "GLY",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "44", " ", "ALA",], [ "45", " ", "ALA",],]
KBD = [ [ "261", " ", "GLU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "267", " ", "CYS",], [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "280", " ", "ARG",], [ "281", " ", "PRO",], [ "282", " ", "THR",], [ "283", " ", "PRO",], [ "284", " ", "CYS",],]
KBE = [ [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "280", " ", "ARG",], [ "284", " ", "CYS",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ARG = 1
GLY = 2
PRO = 2
TRP = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 2
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 2
ARG = 3
ASN = 1
ASP = 3
CYS = 3
GLU = 2
GLY = 6
HIS = 3
ILE = 1
LEU = 4
LYS = 4
MET = 5
PHE = 2
PRO = 5
SER = 3
THR = 2
TRP = 1
TYR = 5
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 19
R2 = 8
R3 = 14
R4 = 5
R5 = 10
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
CYS = 1
ILE = 1
PRO = 1
SER = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 2
ARG = 1
GLY = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ARG = 3
ASN = 1
CYS = 4
ILE = 1
LYS = 2
THR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 1
R2 = 0
R3 = 6
R4 = 0
R5 = 5
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ARG = 1
ASN = 1
ASP = 1
CYS = 3
ILE = 1
LEU = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 2
R2 = 1
R3 = 5
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 1
CYS = 4
SER = 2

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 1
R2 = 0
R3 = 6
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
ARG = 2
GLN = 1
LEU = 1
LYS = 1
PHE = 1
PRO = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 4
R2 = 2
R3 = 1
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 2
CYS = 1
LEU = 1
MET = 1
PHE = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 3
LEU = 1
SER = 3
THR = 1
TRP = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 4
R2 = 1
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ALA = 1
GLU = 1
LEU = 1
MET = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ARG = 1
GLN = 6
GLU = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 1
R2 = 0
R3 = 8
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
GLN = 2
GLU = 1
LEU = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
GLU = 2
GLY = 2
LEU = 1
PHE = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
LYS = 1
TYR = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 1
R2 = 1
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
GLN = 10

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 0
R2 = 0
R3 = 10
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ALA = 6
ARG = 2
ASN = 1
ASP = 1
GLN = 1
GLU = 1
GLY = 1
ILE = 1
LEU = 3
LYS = 1
PRO = 1
SER = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 12
R2 = 2
R3 = 3
R4 = 2
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
LEU = 3
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 1
CYS = 1
GLU = 1
GLY = 1
LYS = 1
SER = 1
VAL = 3

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 5
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ARG = 1
ASP = 1
GLU = 1
LEU = 1
PRO = 1
THR = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
HIS = 1
LEU = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 2
R2 = 0
R3 = 0
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
GLN = 3
LEU = 2

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 2
R2 = 0
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 3
GLY = 1
LEU = 2
PRO = 2
SER = 1

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 8
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
GLN = 2
LEU = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ARG = 1
ASN = 1
ASP = 1
GLN = 1
PHE = 1
SER = 1
TYR = 2

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 0
R2 = 3
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ALA = 1
ARG = 1
GLN = 1
GLU = 2
LEU = 2
LYS = 1
SER = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ALA = 1
ASN = 1
LEU = 2
PHE = 1
PRO = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ARG = 1
ASN = 1
GLN = 2
GLU = 1
ILE = 1
LEU = 1
PHE = 1
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 4
R2 = 1
R3 = 4
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 2
ARG = 1
ASN = 1
GLU = 1
GLY = 1
ILE = 1
PRO = 2

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 6
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBD.RESIDUES]
ALA = 1
ARG = 2
ASP = 1
CYS = 2
GLU = 1
GLY = 1
MET = 1
PRO = 3
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KBD.CLASS]
R1 = 5
R2 = 1
R3 = 4
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBE.RESIDUES]
ARG = 1
CYS = 1
LEU = 2
PRO = 1

[RESULTS.FREQUENCY.KBE.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0
