# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/23_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_23_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 27.86
KAB = 5.62
KAC = 20.95
KAD = 92.66
KAE = 12.53
KAF = 15.34
KAG = 257.04
KAH = 117.5
KAI = 57.24
KAJ = 9.07
KAK = 100.22
KAL = 75.38
KAM = 13.61
KAN = 5.18
KAO = 263.3
KAP = 298.51
KAQ = 8.21
KAR = 167.18
KAS = 39.53
KAT = 106.27
KAU = 88.78
KAV = 13.18
KAW = 42.77
KAX = 267.84
KAY = 587.3
KAZ = 34.56

[RESULTS.AREA]
KAA = 43.35
KAB = 12.75
KAC = 33.98
KAD = 119.86
KAE = 29.65
KAF = 21.53
KAG = 235.5
KAH = 65.38
KAI = 66.76
KAJ = 21.14
KAK = 75.33
KAL = 54.65
KAM = 22.44
KAN = 6.74
KAO = 265.24
KAP = 298.92
KAQ = 15.64
KAR = 188.99
KAS = 38.82
KAT = 105.19
KAU = 102.5
KAV = 11.31
KAW = 29.55
KAX = 319.3
KAY = 477.9
KAZ = 42.88

[RESULTS.MAX_DEPTH]
KAA = 2.81
KAB = 0.6
KAC = 0.85
KAD = 3.12
KAE = 0.6
KAF = 0.85
KAG = 2.68
KAH = 1.34
KAI = 2.94
KAJ = 1.34
KAK = 1.99
KAL = 1.34
KAM = 0.6
KAN = 0.0
KAO = 4.2
KAP = 4.84
KAQ = 0.85
KAR = 3.84
KAS = 0.85
KAT = 1.7
KAU = 2.75
KAV = 0.6
KAW = 0.85
KAX = 5.37
KAY = 3.7
KAZ = 2.16

[RESULTS.AVG_DEPTH]
KAA = 0.9
KAB = 0.18
KAC = 0.2
KAD = 1.07
KAE = 0.1
KAF = 0.2
KAG = 0.83
KAH = 0.37
KAI = 1.07
KAJ = 0.51
KAK = 0.44
KAL = 0.35
KAM = 0.17
KAN = 0.0
KAO = 1.13
KAP = 1.07
KAQ = 0.28
KAR = 1.0
KAS = 0.12
KAT = 0.44
KAU = 0.87
KAV = 0.01
KAW = 0.21
KAX = 1.39
KAY = 1.15
KAZ = 0.77

[RESULTS.AVG_HYDROPATHY]
KAA = 0.54
KAB = 0.81
KAC = -0.68
KAD = 0.5
KAE = -0.6
KAF = 1.29
KAG = -0.0
KAH = 0.33
KAI = -0.24
KAJ = 0.24
KAK = 0.03
KAL = 0.73
KAM = -0.04
KAN = 0.49
KAO = 0.06
KAP = -0.2
KAQ = 0.48
KAR = -0.52
KAS = -0.03
KAT = 0.13
KAU = 0.6
KAV = -0.33
KAW = 0.1
KAX = 0.62
KAY = 0.21
KAZ = 0.86
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "608", " ", "ARG",], [ "611", " ", "ASN",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",],]
KAB = [ [ "563", " ", "CYS",], [ "564", " ", "GLY",], [ "565", " ", "ASP",], [ "606", " ", "LYS",], [ "609", " ", "ARG",], [ "616", " ", "ARG",],]
KAC = [ [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "540", " ", "LEU",],]
KAD = [ [ "527", " ", "TRP",], [ "534", " ", "PRO",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "543", " ", "ALA",], [ "544", " ", "ARG",], [ "545", " ", "ASP",], [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "548", " ", "LEU",],]
KAE = [ [ "582", " ", "VAL",], [ "583", " ", "PHE",], [ "584", " ", "PHE",], [ "585", " ", "LYS",], [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "594", " ", "TYR",], [ "613", " ", "PRO",], [ "617", " ", "LEU",],]
KAF = [ [ "527", " ", "TRP",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "543", " ", "ALA",], [ "544", " ", "ARG",], [ "545", " ", "ASP",],]
KAG = [ [ "558", " ", "LYS",], [ "561", " ", "LEU",], [ "570", " ", "CYS",], [ "571", " ", "HIS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "622", " ", "GLU",], [ "623", " ", "ALA",], [ "624", " ", "GLY",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAH = [ [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "553", " ", "TYR",], [ "557", " ", "GLN",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",],]
KAI = [ [ "572", " ", "TYR",], [ "584", " ", "PHE",], [ "585", " ", "LYS",], [ "588", " ", "ALA",], [ "589", " ", "GLU",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "627", " ", "LEU",], [ "628", " ", "GLY",], [ "631", " ", "PHE",],]
KAJ = [ [ "388", " ", "LYS",], [ "397", " ", "SER",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "404", " ", "ALA",],]
KAK = [ [ "364", " ", "TYR",], [ "365", " ", "TYR",], [ "366", " ", "ASN",], [ "367", " ", "PHE",], [ "368", " ", "PRO",], [ "386", " ", "ARG",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "395", " ", "TYR",],]
KAL = [ [ "385", " ", "ALA",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "401", " ", "ALA",], [ "402", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "468", " ", "GLY",], [ "469", " ", "GLY",],]
KAM = [ [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "442", " ", "GLU",], [ "443", " ", "GLU",], [ "444", " ", "GLY",], [ "445", " ", "GLN",],]
KAN = [ [ "313", " ", "LYS",], [ "315", " ", "GLY",], [ "316", " ", "TYR",], [ "317", " ", "THR",], [ "318", " ", "LYS",],]
KAO = [ [ "217", " ", "ALA",], [ "218", " ", "PRO",], [ "219", " ", "THR",], [ "221", " ", "SER",], [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "228", " ", "GLY",], [ "230", " ", "SER",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",],]
KAP = [ [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "245", " ", "VAL",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "261", " ", "GLU",], [ "262", " ", "GLN",], [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "277", " ", "PRO",], [ "278", " ", "ALA",], [ "279", " ", "VAL",],]
KAQ = [ [ "230", " ", "SER",], [ "231", " ", "THR",], [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "237", " ", "LYS",],]
KAR = [ [ "179", " ", "ALA",], [ "218", " ", "PRO",], [ "219", " ", "THR",], [ "220", " ", "SER",], [ "222", " ", "LYS",], [ "239", " ", "LEU",], [ "243", " ", "VAL",], [ "245", " ", "VAL",], [ "246", " ", "SER",], [ "247", " ", "MET",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "267", " ", "CYS",], [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",], [ "275", " ", "VAL",],]
KAS = [ [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "180", " ", "ASP",], [ "182", " ", "LYS",], [ "183", " ", "ASP",], [ "184", " ", "ILE",],]
KAT = [ [ "97", " ", "PRO",], [ "98", " ", "GLN",], [ "99", " ", "ALA",], [ "100", " ", "HIS",], [ "101", " ", "ARG",], [ "102", " ", "ARG",], [ "129", " ", "ARG",], [ "130", " ", "GLY",], [ "131", " ", "CYS",], [ "132", " ", "VAL",], [ "133", " ", "PRO",], [ "138", " ", "ALA",], [ "139", " ", "VAL",], [ "140", " ", "ALA",], [ "141", " ", "ALA",], [ "142", " ", "SER",],]
KAU = [ [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "88", " ", "GLN",], [ "89", " ", "GLN",], [ "90", " ", "GLN",],]
KAV = [ [ "119", " ", "PRO",], [ "120", " ", "GLN",], [ "121", " ", "SER",], [ "122", " ", "ALA",], [ "123", " ", "LEU",], [ "126", " ", "HIS",],]
KAW = [ [ "104", " ", "PRO",], [ "105", " ", "THR",], [ "106", " ", "GLY",], [ "107", " ", "TYR",], [ "108", " ", "LEU",], [ "109", " ", "VAL",], [ "125", " ", "CYS",], [ "126", " ", "HIS",], [ "127", " ", "PRO",], [ "129", " ", "ARG",],]
KAX = [ [ "13", " ", "ARG",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "35", " ", "GLN",], [ "36", " ", "ASN",], [ "37", " ", "PRO",], [ "38", " ", "GLY",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "49", " ", "PRO",], [ "50", " ", "PRO",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",],]
KAY = [ [ "7", " ", "LEU",], [ "8", " ", "GLY",], [ "9", " ", "ARG",], [ "10", " ", "VAL",], [ "11", " ", "TYR",], [ "12", " ", "PRO",], [ "13", " ", "ARG",], [ "14", " ", "PRO",], [ "15", " ", "PRO",], [ "16", " ", "SER",], [ "17", " ", "LYS",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "21", " ", "GLY",], [ "22", " ", "ALA",], [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "35", " ", "GLN",], [ "36", " ", "ASN",], [ "50", " ", "PRO",], [ "51", " ", "GLY",], [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "62", " ", "GLN",],]
KAZ = [ [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ARG = 3
ASN = 2
CYS = 2
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ARG = 2
ASP = 1
CYS = 1
GLY = 1
LYS = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 1
R2 = 0
R3 = 1
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ASP = 1
GLY = 1
LEU = 1
MET = 1
PRO = 1
SER = 2
TRP = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 3
R2 = 1
R3 = 3
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ARG = 2
ASP = 2
GLY = 1
HIS = 1
LEU = 2
MET = 1
PRO = 1
TRP = 1
VAL = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 6
R2 = 1
R3 = 1
R4 = 2
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ALA = 1
ARG = 1
LEU = 1
LYS = 1
PHE = 2
PRO = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 4
R2 = 3
R3 = 0
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLU = 1
LEU = 1
TRP = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 2
R2 = 1
R3 = 0
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 2
ARG = 2
ASN = 1
CYS = 2
GLU = 1
GLY = 3
HIS = 2
LEU = 3
LYS = 3
MET = 1
PHE = 1
THR = 2
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 9
R2 = 2
R3 = 6
R4 = 1
R5 = 7
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ASP = 1
GLN = 1
HIS = 2
ILE = 1
LEU = 2
LYS = 1
PRO = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 5
R2 = 1
R3 = 1
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 1
GLU = 1
GLY = 1
LEU = 1
LYS = 1
MET = 1
PHE = 2
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 3
R2 = 3
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 3
LYS = 1
SER = 1
TRP = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 3
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ARG = 1
ASN = 2
GLU = 1
LEU = 2
LYS = 1
PHE = 1
PRO = 2
TYR = 3

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 4
R2 = 4
R3 = 2
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 4
ARG = 1
CYS = 1
GLN = 1
GLY = 2
ILE = 1
LEU = 1
LYS = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 8
R2 = 0
R3 = 2
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 1
GLN = 1
GLU = 2
GLY = 1
LEU = 1
PHE = 1
THR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
GLY = 1
LYS = 2
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 1
R2 = 1
R3 = 1
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 3
ASN = 2
ASP = 1
CYS = 1
GLU = 1
GLY = 3
LEU = 4
LYS = 3
PRO = 2
SER = 2
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 13
R2 = 1
R3 = 6
R4 = 2
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 3
ARG = 1
ASN = 1
ASP = 2
CYS = 1
GLN = 1
GLU = 4
GLY = 2
HIS = 1
ILE = 1
LEU = 5
LYS = 2
PRO = 1
SER = 1
VAL = 3

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 15
R2 = 0
R3 = 4
R4 = 6
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ASP = 1
ILE = 1
LYS = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ALA = 1
ASP = 1
CYS = 1
GLY = 2
LEU = 3
LYS = 1
MET = 2
PRO = 2
SER = 2
THR = 1
TYR = 1
VAL = 3

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 11
R2 = 1
R3 = 6
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ASP = 2
CYS = 1
ILE = 1
LEU = 1
LYS = 1
SER = 3

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 4
ARG = 3
CYS = 1
GLN = 1
GLY = 1
HIS = 1
PRO = 2
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 9
R2 = 0
R3 = 3
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ARG = 1
GLN = 7
GLU = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 1
R2 = 0
R3 = 9
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 1
GLN = 1
HIS = 1
LEU = 1
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ARG = 1
CYS = 1
GLY = 1
HIS = 1
LEU = 1
PRO = 2
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 5
R2 = 1
R3 = 2
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ARG = 2
ASN = 1
GLN = 10
GLY = 1
ILE = 1
LEU = 2
PRO = 4
VAL = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 9
R2 = 0
R3 = 11
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 2
ARG = 3
ASN = 2
GLN = 4
GLU = 1
GLY = 3
ILE = 1
LEU = 3
LYS = 1
PHE = 1
PRO = 4
SER = 3
THR = 1
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 15
R2 = 3
R3 = 10
R4 = 1
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
GLN = 8

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 0
R2 = 0
R3 = 8
R4 = 0
R5 = 0
RX = 0
