# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/216_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_216_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 84.89
KAB = 24.41
KAC = 146.45
KAD = 109.94
KAE = 17.93
KAF = 8.42
KAG = 44.28
KAH = 11.45
KAI = 76.68
KAJ = 44.5
KAK = 26.14
KAL = 6.05
KAM = 8.64
KAN = 24.41
KAO = 22.25
KAP = 7.99
KAQ = 469.8
KAR = 6.26
KAS = 79.27
KAT = 867.46
KAU = 54.22
KAV = 9.29
KAW = 6.7
KAX = 11.02

[RESULTS.AREA]
KAA = 91.33
KAB = 31.18
KAC = 118.41
KAD = 126.77
KAE = 23.47
KAF = 5.24
KAG = 40.71
KAH = 20.5
KAI = 96.5
KAJ = 55.58
KAK = 40.88
KAL = 14.1
KAM = 19.23
KAN = 41.53
KAO = 33.8
KAP = 13.94
KAQ = 419.55
KAR = 15.21
KAS = 53.03
KAT = 578.9
KAU = 46.74
KAV = 12.51
KAW = 15.1
KAX = 15.39

[RESULTS.MAX_DEPTH]
KAA = 2.16
KAB = 0.85
KAC = 1.8
KAD = 3.93
KAE = 0.85
KAF = 0.6
KAG = 1.34
KAH = 1.2
KAI = 2.4
KAJ = 2.47
KAK = 1.7
KAL = 0.6
KAM = 1.04
KAN = 1.7
KAO = 1.8
KAP = 0.6
KAQ = 5.4
KAR = 0.85
KAS = 1.34
KAT = 3.55
KAU = 1.34
KAV = 0.6
KAW = 0.0
KAX = 1.2

[RESULTS.AVG_DEPTH]
KAA = 0.66
KAB = 0.1
KAC = 0.46
KAD = 1.19
KAE = 0.29
KAF = 0.02
KAG = 0.33
KAH = 0.37
KAI = 0.56
KAJ = 0.72
KAK = 0.49
KAL = 0.15
KAM = 0.31
KAN = 0.64
KAO = 0.68
KAP = 0.1
KAQ = 1.34
KAR = 0.27
KAS = 0.33
KAT = 0.94
KAU = 0.25
KAV = 0.08
KAW = 0.0
KAX = 0.18

[RESULTS.AVG_HYDROPATHY]
KAA = 0.99
KAB = -0.29
KAC = 0.09
KAD = 0.87
KAE = 0.85
KAF = 1.34
KAG = 0.11
KAH = -0.53
KAI = 0.31
KAJ = -0.35
KAK = 0.28
KAL = 0.15
KAM = 0.3
KAN = -0.28
KAO = 0.02
KAP = 1.11
KAQ = 0.3
KAR = 0.07
KAS = 0.09
KAT = -0.05
KAU = -0.36
KAV = 0.98
KAW = -0.32
KAX = -0.21
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "20", " ", "ARG",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "34", " ", "ILE",], [ "35", " ", "GLN",], [ "36", " ", "ASN",], [ "37", " ", "PRO",], [ "38", " ", "GLY",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "41", " ", "HIS",],]
KAB = [ [ "44", " ", "ALA",], [ "45", " ", "ALA",], [ "47", " ", "ALA",], [ "48", " ", "ALA",], [ "49", " ", "PRO",], [ "51", " ", "GLY",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",],]
KAC = [ [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "69", " ", "GLN",],]
KAD = [ [ "65", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",],]
KAE = [ [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "84", " ", "PRO",], [ "85", " ", "ARG",],]
KAF = [ [ "96", " ", "SER",], [ "97", " ", "PRO",], [ "98", " ", "GLN",], [ "102", " ", "ARG",],]
KAG = [ [ "219", " ", "THR",], [ "220", " ", "SER",], [ "221", " ", "SER",], [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "228", " ", "GLY",],]
KAH = [ [ "584", " ", "PHE",], [ "588", " ", "ALA",], [ "620", " ", "CYS",], [ "621", " ", "TYR",], [ "625", " ", "MET",], [ "627", " ", "LEU",],]
KAI = [ [ "570", " ", "CYS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "626", " ", "THR",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",],]
KAJ = [ [ "365", " ", "TYR",], [ "583", " ", "PHE",], [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "592", " ", "GLN",], [ "593", " ", "LYS",], [ "613", " ", "PRO",], [ "616", " ", "ARG",], [ "617", " ", "LEU",],]
KAK = [ [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",],]
KAL = [ [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "246", " ", "SER",], [ "251", " ", "VAL",],]
KAM = [ [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "256", " ", "HIS",],]
KAN = [ [ "558", " ", "LYS",], [ "567", " ", "ALA",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "575", " ", "LEU",], [ "636", " ", "CYS",], [ "639", " ", "LEU",],]
KAO = [ [ "238", " ", "GLU",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "251", " ", "VAL",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",],]
KAP = [ [ "211", " ", "ALA",], [ "212", " ", "ARG",], [ "214", " ", "ALA",], [ "280", " ", "ARG",], [ "281", " ", "PRO",],]
KAQ = [ [ "372", " ", "ALA",], [ "373", " ", "GLY",], [ "374", " ", "PRO",], [ "375", " ", "PRO",], [ "376", " ", "PRO",], [ "402", " ", "ALA",], [ "403", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "408", " ", "TYR",], [ "409", " ", "GLY",], [ "410", " ", "ASP",], [ "411", " ", "LEU",], [ "412", " ", "ALA",], [ "413", " ", "SER",], [ "414", " ", "LEU",], [ "415", " ", "HIS",], [ "531", " ", "TYR",], [ "534", " ", "PRO",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "546", " ", "HIS",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "571", " ", "HIS",], [ "576", " ", "THR",], [ "577", " ", "CYS",], [ "578", " ", "GLY",], [ "581", " ", "LYS",], [ "582", " ", "VAL",],]
KAR = [ [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "575", " ", "LEU",], [ "639", " ", "LEU",],]
KAS = [ [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "552", " ", "TYR",], [ "556", " ", "PRO",], [ "558", " ", "LYS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "643", " ", "ARG",],]
KAT = [ [ "204", " ", "GLU",], [ "205", " ", "GLY",], [ "206", " ", "SER",], [ "207", " ", "SER",], [ "208", " ", "SER",], [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",], [ "266", " ", "ASP",], [ "267", " ", "CYS",], [ "268", " ", "MET",], [ "269", " ", "TYR",], [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "274", " ", "GLY",], [ "275", " ", "VAL",], [ "276", " ", "PRO",], [ "277", " ", "PRO",], [ "278", " ", "ALA",], [ "279", " ", "VAL",], [ "280", " ", "ARG",], [ "281", " ", "PRO",], [ "282", " ", "THR",], [ "283", " ", "PRO",], [ "285", " ", "ALA",], [ "286", " ", "PRO",], [ "289", " ", "GLU",], [ "290", " ", "CYS",], [ "291", " ", "LYS",], [ "293", " ", "SER",], [ "294", " ", "LEU",], [ "295", " ", "LEU",], [ "318", " ", "LYS",], [ "319", " ", "GLY",], [ "320", " ", "LEU",], [ "321", " ", "GLU",], [ "322", " ", "GLY",], [ "323", " ", "GLU",], [ "324", " ", "SER",], [ "325", " ", "LEU",], [ "326", " ", "GLY",],]
KAU = [ [ "185", " ", "LEU",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",],]
KAV = [ [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "566", " ", "GLU",], [ "567", " ", "ALA",],]
KAW = [ [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",],]
KAX = [ [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "350", " ", "SER",], [ "352", " ", "ALA",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ARG = 2
ASN = 2
GLN = 2
GLY = 1
HIS = 1
ILE = 1
PRO = 2
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 4
R2 = 1
R3 = 5
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 4
GLY = 1
LEU = 2
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 8
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 1
GLN = 10
LEU = 4
SER = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 5
R2 = 0
R3 = 11
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
GLN = 15
GLU = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 0
R2 = 0
R3 = 15
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ARG = 1
GLN = 4
GLU = 1
PRO = 1
THR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 1
R2 = 0
R3 = 5
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ARG = 1
GLN = 1
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ASN = 1
ASP = 1
GLY = 2
LEU = 1
LYS = 1
SER = 2
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 3
R2 = 1
R3 = 4
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
CYS = 1
LEU = 1
MET = 1
PHE = 1
TYR = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 2
R2 = 2
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 2
GLY = 2
LEU = 1
LYS = 1
PHE = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 4
R2 = 2
R3 = 4
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ALA = 1
ARG = 2
GLN = 1
LEU = 1
LYS = 1
PHE = 1
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 3
R2 = 2
R3 = 1
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ALA = 2
CYS = 1
GLU = 1
LEU = 1
LYS = 2
VAL = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 1
CYS = 1
GLU = 1
LEU = 1
LYS = 1
SER = 2
VAL = 2

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 4
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
HIS = 1
LYS = 1
SER = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
CYS = 2
GLY = 1
LEU = 2
LYS = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 4
R2 = 0
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
GLU = 2
LEU = 1
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 2
ARG = 2
PRO = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 3
R2 = 0
R3 = 0
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ALA = 5
ARG = 2
ASP = 2
CYS = 3
GLN = 1
GLU = 1
GLY = 5
HIS = 3
LEU = 3
LYS = 1
MET = 1
PRO = 4
SER = 2
THR = 2
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 18
R2 = 2
R3 = 9
R4 = 3
R5 = 6
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
LEU = 2
LYS = 1
THR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ARG = 1
LEU = 2
LYS = 2
MET = 1
PRO = 2
TYR = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 3
ARG = 2
ASP = 1
CYS = 2
GLU = 4
GLY = 6
LEU = 6
LYS = 2
MET = 1
PRO = 6
SER = 5
THR = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 23
R2 = 1
R3 = 9
R4 = 5
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
GLN = 4
GLU = 1
LEU = 3
MET = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 4
R2 = 0
R3 = 7
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 1
GLN = 1
GLU = 1
LYS = 1
PRO = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ILE = 1
LEU = 1
PHE = 1
PRO = 1
TYR = 2

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 3
R2 = 3
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 1
LEU = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 2
R2 = 1
R3 = 1
R4 = 0
R5 = 0
RX = 0
