# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/29_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_29_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 54.86
KAB = 15.55
KAC = 2275.99
KAD = 104.76
KAE = 19.01
KAF = 31.1
KAG = 18.14
KAH = 12.31
KAI = 36.94
KAJ = 6.91
KAK = 33.7
KAL = 14.26
KAM = 683.86
KAN = 20.3
KAO = 7.34
KAP = 5.62
KAQ = 84.67
KAR = 334.15
KAS = 7.78
KAT = 122.26
KAU = 21.6
KAV = 9.5
KAW = 105.19
KAX = 33.05
KAY = 23.11
KAZ = 7.13
KBA = 36.29
KBB = 17.5
KBC = 294.84
KBD = 49.03
KBE = 30.46

[RESULTS.AREA]
KAA = 32.6
KAB = 26.14
KAC = 1766.92
KAD = 117.5
KAE = 40.62
KAF = 41.37
KAG = 16.43
KAH = 30.58
KAI = 63.23
KAJ = 15.37
KAK = 44.19
KAL = 19.73
KAM = 560.58
KAN = 30.87
KAO = 17.39
KAP = 8.02
KAQ = 62.12
KAR = 171.12
KAS = 16.5
KAT = 68.7
KAU = 21.5
KAV = 6.58
KAW = 89.88
KAX = 36.62
KAY = 45.76
KAZ = 8.63
KBA = 64.73
KBB = 25.16
KBC = 258.47
KBD = 67.2
KBE = 38.48

[RESULTS.MAX_DEPTH]
KAA = 0.6
KAB = 1.2
KAC = 4.72
KAD = 3.23
KAE = 3.55
KAF = 2.16
KAG = 0.85
KAH = 0.0
KAI = 0.0
KAJ = 0.85
KAK = 2.16
KAL = 1.2
KAM = 5.13
KAN = 1.2
KAO = 0.6
KAP = 0.6
KAQ = 1.7
KAR = 2.68
KAS = 0.6
KAT = 1.8
KAU = 1.04
KAV = 0.6
KAW = 1.8
KAX = 1.34
KAY = 0.0
KAZ = 0.6
KBA = 1.47
KBB = 1.34
KBC = 3.23
KBD = 2.24
KBE = 1.34

[RESULTS.AVG_DEPTH]
KAA = 0.16
KAB = 0.38
KAC = 1.18
KAD = 0.86
KAE = 2.07
KAF = 0.62
KAG = 0.12
KAH = 0.0
KAI = 0.0
KAJ = 0.27
KAK = 0.55
KAL = 0.32
KAM = 1.32
KAN = 0.31
KAO = 0.02
KAP = 0.07
KAQ = 0.34
KAR = 0.7
KAS = 0.17
KAT = 0.42
KAU = 0.15
KAV = 0.03
KAW = 0.44
KAX = 0.41
KAY = 0.0
KAZ = 0.07
KBA = 0.43
KBB = 0.36
KBC = 0.96
KBD = 0.81
KBE = 0.39

[RESULTS.AVG_HYDROPATHY]
KAA = -0.55
KAB = -0.2
KAC = 0.02
KAD = -0.44
KAE = 0.98
KAF = 0.8
KAG = -0.48
KAH = -0.4
KAI = 1.3
KAJ = 1.32
KAK = -0.49
KAL = 0.15
KAM = 0.23
KAN = 0.4
KAO = -0.17
KAP = 0.84
KAQ = -0.24
KAR = 0.04
KAS = -1.03
KAT = 0.01
KAU = 0.56
KAV = 0.23
KAW = 0.01
KAX = -0.08
KAY = -0.15
KAZ = 1.44
KBA = 0.7
KBB = -0.5
KBC = 0.54
KBD = 0.84
KBE = 0.86
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "427", " ", "PRO",], [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "431", " ", "ALA",], [ "434", " ", "SER",], [ "435", " ", "TRP",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",],]
KAB = [ [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "443", " ", "GLU",], [ "445", " ", "GLN",], [ "446", " ", "LEU",],]
KAC = [ [ "466", " ", "GLY",], [ "467", " ", "GLY",], [ "468", " ", "GLY",], [ "469", " ", "GLY",], [ "470", " ", "GLY",], [ "491", " ", "ALA",], [ "492", " ", "GLY",], [ "498", " ", "THR",], [ "499", " ", "ALA",], [ "500", " ", "PRO",], [ "501", " ", "ASP",], [ "502", " ", "VAL",], [ "503", " ", "TRP",], [ "504", " ", "TYR",], [ "505", " ", "PRO",], [ "506", " ", "GLY",], [ "507", " ", "GLY",], [ "508", " ", "MET",], [ "509", " ", "VAL",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "513", " ", "PRO",], [ "514", " ", "TYR",], [ "515", " ", "PRO",], [ "516", " ", "SER",], [ "517", " ", "PRO",], [ "518", " ", "THR",], [ "519", " ", "CYS",], [ "520", " ", "VAL",], [ "521", " ", "LYS",], [ "523", " ", "GLU",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "538", " ", "MET",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "541", " ", "GLU",], [ "542", " ", "THR",], [ "544", " ", "ARG",], [ "545", " ", "ASP",], [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "561", " ", "LEU",], [ "568", " ", "SER",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "571", " ", "HIS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "622", " ", "GLU",], [ "623", " ", "ALA",], [ "624", " ", "GLY",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "627", " ", "LEU",], [ "628", " ", "GLY",], [ "630", " ", "LYS",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "642", " ", "THR",], [ "643", " ", "ARG",], [ "644", " ", "PRO",],]
KAD = [ [ "572", " ", "TYR",], [ "587", " ", "ALA",], [ "588", " ", "ALA",], [ "589", " ", "GLU",], [ "590", " ", "GLY",], [ "592", " ", "GLN",], [ "594", " ", "TYR",], [ "617", " ", "LEU",], [ "618", " ", "ARG",], [ "620", " ", "CYS",], [ "621", " ", "TYR",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "627", " ", "LEU",],]
KAE = [ [ "594", " ", "TYR",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "614", " ", "SER",], [ "618", " ", "ARG",],]
KAF = [ [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",], [ "619", " ", "LYS",], [ "622", " ", "GLU",],]
KAG = [ [ "452", " ", "GLY",], [ "453", " ", "GLY",], [ "454", " ", "GLY",], [ "455", " ", "GLY",], [ "476", " ", "GLY",], [ "477", " ", "ALA",], [ "478", " ", "VAL",], [ "480", " ", "PRO",],]
KAH = [ [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "580", " ", "CYS",], [ "583", " ", "PHE",], [ "584", " ", "PHE",], [ "616", " ", "ARG",], [ "620", " ", "CYS",],]
KAI = [ [ "563", " ", "CYS",], [ "604", " ", "ILE",], [ "605", " ", "ASP",], [ "608", " ", "ARG",], [ "609", " ", "ARG",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "619", " ", "LYS",],]
KAJ = [ [ "583", " ", "PHE",], [ "610", " ", "LYS",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "613", " ", "PRO",], [ "616", " ", "ARG",],]
KAK = [ [ "527", " ", "TRP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "538", " ", "MET",],]
KAL = [ [ "567", " ", "ALA",], [ "568", " ", "SER",], [ "571", " ", "HIS",], [ "576", " ", "THR",], [ "577", " ", "CYS",], [ "578", " ", "GLY",], [ "580", " ", "CYS",], [ "581", " ", "LYS",],]
KAM = [ [ "334", " ", "GLY",], [ "335", " ", "SER",], [ "339", " ", "LEU",], [ "340", " ", "GLU",], [ "341", " ", "LEU",], [ "342", " ", "PRO",], [ "348", " ", "TYR",], [ "376", " ", "PRO",], [ "377", " ", "PRO",], [ "379", " ", "PRO",], [ "381", " ", "PRO",], [ "382", " ", "HIS",], [ "383", " ", "PRO",], [ "384", " ", "HIS",], [ "385", " ", "ALA",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "393", " ", "LEU",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "402", " ", "ALA",], [ "478", " ", "VAL",], [ "479", " ", "ALA",], [ "480", " ", "PRO",], [ "481", " ", "TYR",], [ "482", " ", "GLY",], [ "483", " ", "TYR",], [ "484", " ", "THR",],]
KAN = [ [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",], [ "386", " ", "ARG",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",],]
KAO = [ [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "389", " ", "LEU",], [ "397", " ", "SER",], [ "398", " ", "ALA",],]
KAP = [ [ "313", " ", "LYS",], [ "316", " ", "TYR",], [ "322", " ", "GLY",], [ "323", " ", "GLU",], [ "324", " ", "SER",],]
KAQ = [ [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "259", " ", "PRO",], [ "316", " ", "TYR",], [ "317", " ", "THR",], [ "318", " ", "LYS",],]
KAR = [ [ "202", " ", "VAL",], [ "203", " ", "SER",], [ "205", " ", "GLY",], [ "206", " ", "SER",], [ "207", " ", "SER",], [ "208", " ", "SER",], [ "209", " ", "GLY",], [ "210", " ", "ARG",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "272", " ", "LEU",], [ "304", " ", "GLU",], [ "305", " ", "ASP",], [ "306", " ", "THR",], [ "307", " ", "ALA",], [ "308", " ", "GLU",], [ "309", " ", "TYR",],]
KAS = [ [ "245", " ", "VAL",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",],]
KAT = [ [ "143", " ", "LYS",], [ "145", " ", "LEU",], [ "146", " ", "PRO",], [ "158", " ", "SER",], [ "159", " ", "ALA",], [ "160", " ", "ALA",], [ "161", " ", "PRO",], [ "162", " ", "SER",], [ "163", " ", "THR",], [ "164", " ", "LEU",], [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "168", " ", "GLY",],]
KAU = [ [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "199", " ", "GLN",], [ "200", " ", "GLU",], [ "201", " ", "ALA",], [ "202", " ", "VAL",],]
KAV = [ [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "216", " ", "GLY",], [ "217", " ", "ALA",],]
KAW = [ [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",], [ "197", " ", "GLN",], [ "198", " ", "GLN",], [ "199", " ", "GLN",],]
KAX = [ [ "115", " ", "GLN",], [ "116", " ", "PRO",], [ "117", " ", "SER",], [ "172", " ", "PRO",], [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",],]
KAY = [ [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "181", " ", "LEU",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "192", " ", "GLN",],]
KAZ = [ [ "2", " ", "GLU",], [ "4", " ", "GLN",], [ "9", " ", "ARG",],]
KBA = [ [ "19", " ", "TYR",], [ "20", " ", "ARG",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "31", " ", "ARG",],]
KBB = [ [ "26", " ", "LEU",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "34", " ", "ILE",],]
KBC = [ [ "24", " ", "GLN",], [ "30", " ", "VAL",], [ "31", " ", "ARG",], [ "36", " ", "ASN",], [ "37", " ", "PRO",], [ "38", " ", "GLY",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "44", " ", "ALA",], [ "45", " ", "ALA",], [ "46", " ", "SER",], [ "48", " ", "ALA",], [ "49", " ", "PRO",], [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "62", " ", "GLN",], [ "63", " ", "GLN",],]
KBD = [ [ "39", " ", "PRO",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "62", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",],]
KBE = [ [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 3
HIS = 1
LEU = 1
PHE = 1
PRO = 1
SER = 2
THR = 1
TRP = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 5
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
GLN = 1
GLU = 1
HIS = 1
LEU = 2
PHE = 1
THR = 2

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 3
R2 = 1
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 4
ARG = 5
ASN = 1
ASP = 4
CYS = 4
GLN = 1
GLU = 3
GLY = 14
HIS = 3
ILE = 1
LEU = 6
LYS = 5
MET = 5
PHE = 2
PRO = 9
SER = 4
THR = 6
TRP = 2
TYR = 6
VAL = 6

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 40
R2 = 10
R3 = 21
R4 = 7
R5 = 13
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 2
ARG = 1
CYS = 1
GLN = 1
GLU = 1
GLY = 1
LEU = 2
MET = 1
THR = 1
TYR = 3

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 5
R2 = 3
R3 = 4
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ARG = 2
ASN = 1
ASP = 1
CYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 0
R2 = 1
R3 = 3
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ARG = 1
ASN = 1
ASP = 1
CYS = 2
GLU = 1
ILE = 1
LYS = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 1
R2 = 0
R3 = 5
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 1
GLY = 5
PRO = 1
VAL = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 8
R2 = 0
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ARG = 1
CYS = 3
ILE = 1
PHE = 2

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 1
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ARG = 3
ASP = 1
CYS = 2
ILE = 1
LYS = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 1
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ARG = 1
ASN = 1
CYS = 1
LYS = 1
PHE = 1
PRO = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 1
R2 = 1
R3 = 2
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
GLY = 1
MET = 1
PRO = 1
SER = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 2
R2 = 2
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 1
CYS = 2
GLY = 1
HIS = 1
LYS = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 6
ARG = 1
ASN = 1
ASP = 1
GLU = 2
GLY = 3
HIS = 2
ILE = 1
LEU = 4
LYS = 1
PRO = 8
SER = 2
THR = 1
TRP = 1
TYR = 4
VAL = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 23
R2 = 5
R3 = 4
R4 = 3
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
ARG = 1
LEU = 1
SER = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 2
R2 = 2
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 1
ARG = 1
ILE = 1
LEU = 1
SER = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
GLU = 1
GLY = 1
LYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 1
R2 = 1
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ALA = 2
GLU = 1
HIS = 1
LEU = 1
LYS = 2
PRO = 1
SER = 1
THR = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 6
R2 = 1
R3 = 2
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ALA = 2
ARG = 1
ASP = 1
GLU = 3
GLY = 3
LEU = 2
SER = 4
THR = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 9
R2 = 1
R3 = 5
R4 = 4
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 1
GLU = 1
GLY = 1
LEU = 1
VAL = 2

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 2
GLY = 1
LEU = 4
LYS = 1
PRO = 2
SER = 3
THR = 1

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 9
R2 = 0
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
GLN = 4
GLU = 1
VAL = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 1
GLN = 2
GLY = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
GLN = 6
GLU = 1
LEU = 3
MET = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 4
R2 = 0
R3 = 10
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
GLN = 1
GLY = 1
LEU = 1
PRO = 2
SER = 3

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 4
R2 = 0
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 2
GLN = 1
ILE = 1
LEU = 2
SER = 2

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 5
R2 = 0
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ARG = 1
GLN = 1
GLU = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 0
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ARG = 2
ASN = 1
GLN = 2
LEU = 1
PHE = 1
SER = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 2
R2 = 2
R3 = 4
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ARG = 1
GLU = 1
ILE = 1
LEU = 1
SER = 1
VAL = 2

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 4
ARG = 2
ASN = 1
GLN = 7
GLY = 1
LEU = 4
PRO = 3
SER = 2
VAL = 1

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 13
R2 = 0
R3 = 10
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBD.RESIDUES]
GLN = 8
PRO = 1

[RESULTS.FREQUENCY.KBD.CLASS]
R1 = 1
R2 = 0
R3 = 8
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBE.RESIDUES]
GLN = 7

[RESULTS.FREQUENCY.KBE.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0
