# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/3_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_3_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 270.22
KAB = 185.11
KAC = 19.01
KAD = 19.87
KAE = 6.91
KAF = 12.31
KAG = 64.15
KAH = 85.97
KAI = 20.95
KAJ = 8.42
KAK = 29.81
KAL = 64.8
KAM = 54.65
KAN = 5.62
KAO = 16.42
KAP = 20.3
KAQ = 17.5
KAR = 9.5
KAS = 104.54
KAT = 17.28
KAU = 13.82
KAV = 56.16
KAW = 53.57
KAX = 9.07
KAY = 19.22
KAZ = 18.14
KBA = 6.48
KBB = 22.9
KBC = 251.64

[RESULTS.AREA]
KAA = 266.64
KAB = 176.25
KAC = 29.81
KAD = 29.92
KAE = 12.58
KAF = 30.58
KAG = 105.85
KAH = 59.48
KAI = 31.89
KAJ = 9.79
KAK = 52.58
KAL = 92.07
KAM = 51.32
KAN = 13.64
KAO = 21.73
KAP = 38.28
KAQ = 16.12
KAR = 13.78
KAS = 100.63
KAT = 27.45
KAU = 18.14
KAV = 38.99
KAW = 53.65
KAX = 20.3
KAY = 26.73
KAZ = 23.9
KBA = 16.81
KBB = 28.36
KBC = 150.23

[RESULTS.MAX_DEPTH]
KAA = 4.02
KAB = 3.23
KAC = 1.2
KAD = 1.9
KAE = 0.85
KAF = 0.0
KAG = 6.63
KAH = 1.34
KAI = 1.47
KAJ = 0.6
KAK = 0.0
KAL = 3.0
KAM = 1.47
KAN = 0.6
KAO = 1.2
KAP = 0.85
KAQ = 0.6
KAR = 0.6
KAS = 2.47
KAT = 0.6
KAU = 0.85
KAV = 1.34
KAW = 1.7
KAX = 1.2
KAY = 1.7
KAZ = 0.6
KBA = 0.85
KBB = 1.2
KBC = 2.55

[RESULTS.AVG_DEPTH]
KAA = 1.25
KAB = 0.85
KAC = 0.3
KAD = 0.68
KAE = 0.24
KAF = 0.0
KAG = 2.53
KAH = 0.23
KAI = 0.51
KAJ = 0.09
KAK = 0.0
KAL = 0.74
KAM = 0.28
KAN = 0.18
KAO = 0.21
KAP = 0.19
KAQ = 0.06
KAR = 0.12
KAS = 0.91
KAT = 0.04
KAU = 0.18
KAV = 0.29
KAW = 0.46
KAX = 0.26
KAY = 0.51
KAZ = 0.13
KBA = 0.26
KBB = 0.25
KBC = 0.75

[RESULTS.AVG_HYDROPATHY]
KAA = 0.06
KAB = -0.12
KAC = 0.63
KAD = -0.74
KAE = 0.66
KAF = -0.95
KAG = 0.31
KAH = -0.26
KAI = 0.49
KAJ = 1.42
KAK = 0.61
KAL = -0.08
KAM = -0.47
KAN = -0.56
KAO = 0.23
KAP = -0.56
KAQ = -0.08
KAR = -0.28
KAS = 0.05
KAT = -0.4
KAU = 1.54
KAV = 0.51
KAW = 0.86
KAX = 0.84
KAY = 0.85
KAZ = -0.68
KBA = 0.31
KBB = -0.82
KBC = -0.03
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "544", " ", "ARG",], [ "545", " ", "ASP",], [ "546", " ", "HIS",], [ "547", " ", "VAL",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "555", " ", "PRO",], [ "556", " ", "PRO",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "638", " ", "HIS",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAB = [ [ "433", " ", "SER",], [ "435", " ", "TRP",], [ "558", " ", "LYS",], [ "570", " ", "CYS",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",],]
KAC = [ [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "362", " ", "ARG",], [ "363", " ", "ASP",], [ "364", " ", "TYR",], [ "366", " ", "ASN",],]
KAD = [ [ "561", " ", "LEU",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "635", " ", "ASN",], [ "639", " ", "LEU",],]
KAE = [ [ "359", " ", "TYR",], [ "360", " ", "GLN",], [ "367", " ", "PHE",], [ "368", " ", "PRO",], [ "369", " ", "LEU",],]
KAF = [ [ "561", " ", "LEU",], [ "562", " ", "ILE",], [ "572", " ", "TYR",], [ "574", " ", "ALA",], [ "576", " ", "THR",], [ "620", " ", "CYS",], [ "623", " ", "ALA",], [ "624", " ", "GLY",], [ "625", " ", "MET",],]
KAG = [ [ "596", " ", "CYS",], [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "612", " ", "CYS",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KAH = [ [ "467", " ", "GLY",], [ "468", " ", "GLY",], [ "469", " ", "GLY",], [ "470", " ", "GLY",], [ "474", " ", "GLU",], [ "475", " ", "ALA",], [ "477", " ", "ALA",], [ "478", " ", "VAL",], [ "479", " ", "ALA",], [ "480", " ", "PRO",], [ "481", " ", "TYR",], [ "482", " ", "GLY",], [ "483", " ", "TYR",], [ "484", " ", "THR",], [ "485", " ", "ARG",], [ "539", " ", "ARG",],]
KAI = [ [ "593", " ", "LYS",], [ "594", " ", "TYR",], [ "614", " ", "SER",], [ "617", " ", "LEU",], [ "618", " ", "ARG",],]
KAJ = [ [ "287", " ", "LEU",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "390", " ", "GLU",],]
KAK = [ [ "563", " ", "CYS",], [ "604", " ", "ILE",], [ "608", " ", "ARG",], [ "609", " ", "ARG",], [ "615", " ", "CYS",], [ "616", " ", "ARG",],]
KAL = [ [ "468", " ", "GLY",], [ "469", " ", "GLY",], [ "470", " ", "GLY",], [ "472", " ", "GLY",], [ "483", " ", "TYR",], [ "485", " ", "ARG",], [ "486", " ", "PRO",], [ "487", " ", "PRO",], [ "489", " ", "GLY",], [ "490", " ", "LEU",], [ "491", " ", "ALA",], [ "492", " ", "GLY",], [ "493", " ", "GLN",], [ "494", " ", "GLU",], [ "495", " ", "SER",],]
KAM = [ [ "425", " ", "GLY",], [ "426", " ", "SER",], [ "430", " ", "ALA",], [ "433", " ", "SER",], [ "434", " ", "SER",], [ "439", " ", "PHE",], [ "447", " ", "TYR",], [ "449", " ", "PRO",], [ "450", " ", "CYS",], [ "451", " ", "GLY",], [ "452", " ", "GLY",],]
KAN = [ [ "583", " ", "PHE",], [ "587", " ", "ALA",], [ "594", " ", "TYR",], [ "613", " ", "PRO",], [ "617", " ", "LEU",],]
KAO = [ [ "521", " ", "LYS",], [ "522", " ", "SER",], [ "523", " ", "GLU",], [ "524", " ", "MET",], [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "527", " ", "TRP",], [ "528", " ", "MET",],]
KAP = [ [ "393", " ", "LEU",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "400", " ", "ALA",], [ "401", " ", "ALA",], [ "402", " ", "ALA",], [ "405", " ", "GLN",],]
KAQ = [ [ "241", " ", "LYS",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "250", " ", "GLY",], [ "254", " ", "LEU",],]
KAR = [ [ "222", " ", "LYS",], [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "229", " ", "THR",], [ "230", " ", "SER",], [ "232", " ", "ILE",],]
KAS = [ [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",], [ "190", " ", "THR",], [ "191", " ", "MET",], [ "192", " ", "GLN",], [ "193", " ", "LEU",], [ "194", " ", "LEU",], [ "195", " ", "GLN",], [ "196", " ", "GLN",],]
KAT = [ [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "177", " ", "CYS",], [ "178", " ", "SER",], [ "179", " ", "ALA",], [ "181", " ", "LEU",],]
KAU = [ [ "85", " ", "ARG",], [ "89", " ", "GLN",], [ "90", " ", "GLN",], [ "91", " ", "GLN",], [ "92", " ", "GLY",], [ "94", " ", "ASP",],]
KAV = [ [ "79", " ", "GLN",], [ "81", " ", "GLU",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "87", " ", "GLN",], [ "88", " ", "GLN",],]
KAW = [ [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",],]
KAX = [ [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",],]
KAY = [ [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",],]
KAZ = [ [ "18", " ", "THR",], [ "20", " ", "ARG",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "29", " ", "SER",], [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "34", " ", "ILE",],]
KBA = [ [ "14", " ", "PRO",], [ "15", " ", "PRO",], [ "16", " ", "SER",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "20", " ", "ARG",],]
KBB = [ [ "20", " ", "ARG",], [ "21", " ", "GLY",], [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",],]
KBC = [ [ "9", " ", "ARG",], [ "40", " ", "ARG",], [ "45", " ", "ALA",], [ "47", " ", "ALA",], [ "48", " ", "ALA",], [ "49", " ", "PRO",], [ "51", " ", "GLY",], [ "52", " ", "ALA",], [ "53", " ", "SER",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ARG = 2
ASP = 2
GLN = 1
HIS = 2
ILE = 1
LEU = 1
LYS = 2
MET = 1
PRO = 3
THR = 2
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 6
R2 = 2
R3 = 4
R4 = 2
R5 = 6
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 2
GLY = 2
LEU = 1
LYS = 2
PHE = 1
SER = 1
TRP = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 5
R2 = 3
R3 = 4
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ARG = 1
ASN = 1
ASP = 1
GLN = 1
TYR = 2

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 0
R2 = 2
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ASN = 1
GLY = 1
LEU = 3

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 5
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
GLN = 1
LEU = 1
PHE = 1
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 2
R2 = 2
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 2
CYS = 1
GLY = 1
ILE = 1
LEU = 1
MET = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 5
R2 = 1
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ARG = 2
ASN = 1
ASP = 1
CYS = 4
ILE = 1
LYS = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 1
R2 = 0
R3 = 8
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 3
ARG = 2
GLU = 1
GLY = 5
PRO = 1
THR = 1
TYR = 2
VAL = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 10
R2 = 2
R3 = 1
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ARG = 1
LEU = 1
LYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 1
R2 = 1
R3 = 1
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ARG = 1
GLU = 1
ILE = 1
LEU = 2
LYS = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 3
R2 = 0
R3 = 0
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ARG = 3
CYS = 2
ILE = 1

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 1
R2 = 0
R3 = 2
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 1
ARG = 1
GLN = 1
GLU = 1
GLY = 6
LEU = 1
PRO = 2
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 10
R2 = 1
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 1
CYS = 1
GLY = 3
PHE = 1
PRO = 1
SER = 3
TYR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 5
R2 = 2
R3 = 4
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ALA = 1
LEU = 1
PHE = 1
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 3
R2 = 2
R3 = 0
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
GLU = 1
GLY = 1
LYS = 1
MET = 2
PRO = 1
SER = 1
TRP = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 2
R2 = 1
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
ALA = 4
GLN = 1
GLY = 1
LEU = 1
SER = 1
TRP = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 6
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
GLY = 1
LEU = 1
LYS = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ASN = 1
ASP = 1
ILE = 1
LEU = 1
LYS = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 2
R2 = 1
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 1
GLN = 3
GLU = 1
ILE = 1
LEU = 3
MET = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 5
R2 = 0
R3 = 7
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 1
CYS = 1
LEU = 2
SER = 2

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 3
R2 = 0
R3 = 3
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ARG = 1
ASP = 1
GLN = 3
GLY = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 1
R2 = 0
R3 = 3
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ARG = 1
GLN = 4
GLU = 1
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 1
R2 = 0
R3 = 6
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
GLN = 12

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 0
R2 = 0
R3 = 12
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
GLN = 5

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 0
R2 = 0
R3 = 5
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
GLN = 7

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 0
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ARG = 2
GLU = 1
ILE = 1
LEU = 1
PHE = 1
SER = 1
THR = 1
VAL = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ARG = 1
PRO = 2
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 2
R2 = 1
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ARG = 1
ASN = 1
GLN = 1
GLY = 1
LEU = 1
PHE = 2

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 2
R2 = 2
R3 = 2
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 4
ARG = 2
GLN = 4
GLY = 1
LEU = 4
PRO = 1
SER = 1

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 10
R2 = 0
R3 = 5
R4 = 0
R5 = 2
RX = 0
