# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/222_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_222_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 6.7
KAB = 53.14
KAC = 20.95
KAD = 174.53
KAE = 27.22
KAF = 8.64
KAG = 23.33
KAH = 11.23
KAI = 38.02
KAJ = 21.82
KAK = 6.48
KAL = 45.14
KAM = 14.47
KAN = 11.45
KAO = 7.13
KAP = 14.9
KAQ = 320.98
KAR = 44.71
KAS = 17.71
KAT = 17.5
KAU = 13.61
KAV = 6.26
KAW = 295.92
KAX = 38.45
KAY = 42.12
KAZ = 10.58
KBA = 6.7
KBB = 146.45
KBC = 7.99
KBD = 34.13
KBE = 25.27
KBF = 17.5
KBG = 224.42

[RESULTS.AREA]
KAA = 13.62
KAB = 89.68
KAC = 36.55
KAD = 158.67
KAE = 43.59
KAF = 18.11
KAG = 31.93
KAH = 15.59
KAI = 46.89
KAJ = 31.56
KAK = 14.22
KAL = 53.68
KAM = 20.62
KAN = 16.69
KAO = 11.46
KAP = 25.74
KAQ = 274.88
KAR = 35.7
KAS = 23.9
KAT = 26.35
KAU = 28.03
KAV = 7.63
KAW = 310.23
KAX = 55.54
KAY = 44.61
KAZ = 9.72
KBA = 11.84
KBB = 109.83
KBC = 14.0
KBD = 32.43
KBE = 22.92
KBF = 6.22
KBG = 198.9

[RESULTS.MAX_DEPTH]
KAA = 0.6
KAB = 0.0
KAC = 1.2
KAD = 3.55
KAE = 1.47
KAF = 0.85
KAG = 1.7
KAH = 0.6
KAI = 1.34
KAJ = 1.34
KAK = 0.6
KAL = 2.08
KAM = 0.85
KAN = 0.6
KAO = 0.6
KAP = 1.2
KAQ = 3.39
KAR = 1.2
KAS = 0.6
KAT = 1.2
KAU = 1.04
KAV = 0.6
KAW = 5.82
KAX = 1.7
KAY = 2.47
KAZ = 0.6
KBA = 0.6
KBB = 2.55
KBC = 0.6
KBD = 0.85
KBE = 0.85
KBF = 0.6
KBG = 2.47

[RESULTS.AVG_DEPTH]
KAA = 0.21
KAB = 0.0
KAC = 0.31
KAD = 0.71
KAE = 0.44
KAF = 0.14
KAG = 0.35
KAH = 0.12
KAI = 0.32
KAJ = 0.3
KAK = 0.16
KAL = 0.68
KAM = 0.3
KAN = 0.18
KAO = 0.07
KAP = 0.36
KAQ = 1.06
KAR = 0.33
KAS = 0.04
KAT = 0.38
KAU = 0.19
KAV = 0.02
KAW = 1.73
KAX = 0.53
KAY = 0.66
KAZ = 0.13
KBA = 0.08
KBB = 0.7
KBC = 0.19
KBD = 0.15
KBE = 0.22
KBF = 0.07
KBG = 0.45

[RESULTS.AVG_HYDROPATHY]
KAA = -0.27
KAB = -0.23
KAC = 0.24
KAD = 0.02
KAE = 0.17
KAF = -0.04
KAG = 0.72
KAH = 0.05
KAI = 0.7
KAJ = 0.3
KAK = -0.42
KAL = 0.31
KAM = -0.41
KAN = 0.84
KAO = 1.55
KAP = 0.59
KAQ = -0.32
KAR = 1.06
KAS = -0.12
KAT = -0.22
KAU = 0.92
KAV = 0.24
KAW = 0.21
KAX = -0.31
KAY = 0.2
KAZ = 0.32
KBA = -0.01
KBB = -0.22
KBC = -0.65
KBD = -0.13
KBE = -0.48
KBF = -0.3
KBG = -0.65
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "572", " ", "TYR",], [ "584", " ", "PHE",], [ "585", " ", "LYS",], [ "589", " ", "GLU",], [ "627", " ", "LEU",],]
KAB = [ [ "562", " ", "ILE",], [ "571", " ", "HIS",], [ "572", " ", "TYR",], [ "574", " ", "ALA",], [ "576", " ", "THR",], [ "580", " ", "CYS",], [ "581", " ", "LYS",], [ "584", " ", "PHE",], [ "585", " ", "LYS",], [ "620", " ", "CYS",], [ "624", " ", "GLY",], [ "625", " ", "MET",],]
KAC = [ [ "563", " ", "CYS",], [ "564", " ", "GLY",], [ "565", " ", "ASP",], [ "579", " ", "SER",], [ "583", " ", "PHE",], [ "605", " ", "ASP",], [ "608", " ", "ARG",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "616", " ", "ARG",],]
KAD = [ [ "561", " ", "LEU",], [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "624", " ", "GLY",], [ "625", " ", "MET",], [ "626", " ", "THR",], [ "627", " ", "LEU",], [ "628", " ", "GLY",], [ "630", " ", "LYS",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",],]
KAE = [ [ "596", " ", "CYS",], [ "597", " ", "ALA",], [ "598", " ", "SER",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "609", " ", "ARG",], [ "611", " ", "ASN",], [ "612", " ", "CYS",], [ "613", " ", "PRO",], [ "614", " ", "SER",], [ "615", " ", "CYS",],]
KAF = [ [ "558", " ", "LYS",], [ "575", " ", "LEU",], [ "638", " ", "HIS",], [ "639", " ", "LEU",],]
KAG = [ [ "596", " ", "CYS",], [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "602", " ", "CYS",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KAH = [ [ "24", " ", "GLN",], [ "25", " ", "ASN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "31", " ", "ARG",],]
KAI = [ [ "20", " ", "ARG",], [ "30", " ", "VAL",], [ "31", " ", "ARG",], [ "32", " ", "GLU",], [ "33", " ", "VAL",], [ "36", " ", "ASN",], [ "41", " ", "HIS",],]
KAJ = [ [ "16", " ", "SER",], [ "17", " ", "LYS",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "20", " ", "ARG",], [ "23", " ", "PHE",], [ "24", " ", "GLN",], [ "25", " ", "ASN",],]
KAK = [ [ "52", " ", "ALA",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "58", " ", "GLN",],]
KAL = [ [ "57", " ", "LEU",], [ "58", " ", "GLN",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "63", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",],]
KAM = [ [ "1", " ", "MET",], [ "3", " ", "VAL",], [ "4", " ", "GLN",], [ "5", " ", "LEU",], [ "10", " ", "VAL",], [ "11", " ", "TYR",], [ "12", " ", "PRO",],]
KAN = [ [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "77", " ", "GLN",],]
KAO = [ [ "537", " ", "ASP",], [ "538", " ", "MET",], [ "539", " ", "ARG",],]
KAP = [ [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "80", " ", "GLN",], [ "82", " ", "THR",], [ "83", " ", "SER",], [ "84", " ", "PRO",],]
KAQ = [ [ "422", " ", "PRO",], [ "423", " ", "GLY",], [ "424", " ", "SER",], [ "425", " ", "GLY",], [ "426", " ", "SER",], [ "427", " ", "PRO",], [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "430", " ", "ALA",], [ "500", " ", "PRO",], [ "501", " ", "ASP",], [ "502", " ", "VAL",], [ "503", " ", "TRP",], [ "504", " ", "TYR",], [ "505", " ", "PRO",], [ "506", " ", "GLY",], [ "507", " ", "GLY",], [ "508", " ", "MET",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",], [ "513", " ", "PRO",], [ "514", " ", "TYR",], [ "515", " ", "PRO",], [ "516", " ", "SER",],]
KAR = [ [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "87", " ", "GLN",], [ "89", " ", "GLN",], [ "90", " ", "GLN",], [ "92", " ", "GLY",], [ "93", " ", "GLU",],]
KAS = [ [ "428", " ", "SER",], [ "429", " ", "ALA",], [ "431", " ", "ALA",], [ "433", " ", "SER",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "516", " ", "SER",],]
KAT = [ [ "499", " ", "ALA",], [ "500", " ", "PRO",], [ "501", " ", "ASP",], [ "502", " ", "VAL",], [ "503", " ", "TRP",], [ "510", " ", "SER",], [ "511", " ", "ARG",], [ "512", " ", "VAL",],]
KAU = [ [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "390", " ", "GLU",], [ "411", " ", "LEU",], [ "416", " ", "GLY",], [ "417", " ", "ALA",], [ "504", " ", "TYR",], [ "505", " ", "PRO",],]
KAV = [ [ "478", " ", "VAL",], [ "479", " ", "ALA",], [ "480", " ", "PRO",], [ "485", " ", "ARG",], [ "486", " ", "PRO",], [ "487", " ", "PRO",],]
KAW = [ [ "378", " ", "PRO",], [ "384", " ", "HIS",], [ "386", " ", "ARG",], [ "387", " ", "ILE",], [ "388", " ", "LYS",], [ "389", " ", "LEU",], [ "391", " ", "ASN",], [ "392", " ", "PRO",], [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "396", " ", "GLY",], [ "397", " ", "SER",], [ "398", " ", "ALA",], [ "399", " ", "TRP",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "408", " ", "TYR",], [ "409", " ", "GLY",], [ "410", " ", "ASP",], [ "411", " ", "LEU",], [ "413", " ", "SER",], [ "414", " ", "LEU",], [ "415", " ", "HIS",], [ "455", " ", "GLY",], [ "456", " ", "GLY",], [ "457", " ", "GLY",],]
KAX = [ [ "376", " ", "PRO",], [ "377", " ", "PRO",], [ "378", " ", "PRO",], [ "402", " ", "ALA",], [ "403", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "462", " ", "GLY",], [ "464", " ", "GLY",],]
KAY = [ [ "397", " ", "SER",], [ "402", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "459", " ", "GLY",], [ "460", " ", "GLY",], [ "461", " ", "GLY",], [ "462", " ", "GLY",],]
KAZ = [ [ "350", " ", "SER",], [ "353", " ", "LEU",], [ "354", " ", "ASP",], [ "355", " ", "GLU",], [ "356", " ", "ALA",], [ "357", " ", "ALA",],]
KBA = [ [ "343", " ", "SER",], [ "344", " ", "THR",], [ "346", " ", "SER",], [ "348", " ", "TYR",], [ "349", " ", "LYS",], [ "350", " ", "SER",],]
KBB = [ [ "229", " ", "THR",], [ "231", " ", "THR",], [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "243", " ", "VAL",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "251", " ", "VAL",],]
KBC = [ [ "245", " ", "VAL",], [ "246", " ", "SER",], [ "252", " ", "GLU",], [ "253", " ", "ALA",], [ "254", " ", "LEU",], [ "255", " ", "GLU",],]
KBD = [ [ "223", " ", "ASP",], [ "224", " ", "ASN",], [ "225", " ", "TYR",], [ "226", " ", "LEU",], [ "227", " ", "GLY",], [ "240", " ", "CYS",], [ "241", " ", "LYS",], [ "242", " ", "ALA",], [ "243", " ", "VAL",],]
KBE = [ [ "246", " ", "SER",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "258", " ", "SER",], [ "259", " ", "PRO",],]
KBF = [ [ "257", " ", "LEU",], [ "258", " ", "SER",], [ "262", " ", "GLN",], [ "263", " ", "LEU",],]
KBG = [ [ "155", " ", "GLU",], [ "156", " ", "ASP",], [ "157", " ", "ASP",], [ "159", " ", "ALA",], [ "160", " ", "ALA",], [ "161", " ", "PRO",], [ "164", " ", "LEU",], [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "168", " ", "GLY",], [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "172", " ", "PRO",], [ "173", " ", "GLY",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "176", " ", "SER",], [ "177", " ", "CYS",], [ "181", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "193", " ", "LEU",], [ "194", " ", "LEU",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
GLU = 1
LEU = 1
LYS = 1
PHE = 1
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 1
R2 = 2
R3 = 0
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
CYS = 2
GLY = 1
HIS = 1
ILE = 1
LYS = 2
MET = 1
PHE = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 3
R2 = 2
R3 = 4
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ARG = 3
ASP = 2
CYS = 1
GLY = 1
LYS = 1
PHE = 1
SER = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 1
R2 = 1
R3 = 2
R4 = 2
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 1
GLY = 4
HIS = 1
LEU = 4
LYS = 2
MET = 1
PHE = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 10
R2 = 2
R3 = 4
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
CYS = 4
PRO = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 2
R2 = 0
R3 = 8
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
HIS = 1
LEU = 2
LYS = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 2
R2 = 0
R3 = 0
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ARG = 2
ASN = 1
CYS = 3
LYS = 1
SER = 2

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 0
R2 = 0
R3 = 6
R4 = 0
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ARG = 1
ASN = 1
GLN = 2
LEU = 1
PHE = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 2
R2 = 1
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ARG = 2
ASN = 1
GLU = 1
HIS = 1
VAL = 2

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ARG = 1
ASN = 1
GLN = 1
LYS = 1
PHE = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 0
R2 = 2
R3 = 4
R4 = 0
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ALA = 1
GLN = 1
LEU = 3

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 4
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
GLN = 7
LEU = 1

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 1
R2 = 0
R3 = 7
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
GLN = 1
LEU = 1
MET = 1
PRO = 1
TYR = 1
VAL = 2

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
GLN = 5

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 0
R2 = 0
R3 = 5
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ARG = 1
ASP = 1
MET = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 0
R2 = 0
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
GLN = 4
PRO = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 1
R2 = 0
R3 = 6
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ALA = 2
ARG = 1
ASP = 1
GLY = 4
MET = 1
PRO = 6
SER = 5
TRP = 1
TYR = 2
VAL = 2

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 14
R2 = 3
R3 = 6
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
ARG = 1
GLN = 4
GLU = 1
GLY = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 1
R2 = 0
R3 = 4
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 2
HIS = 1
SER = 3
THR = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 2
R2 = 0
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
PRO = 1
SER = 1
TRP = 1
VAL = 2

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 4
R2 = 1
R3 = 1
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
GLU = 1
GLY = 1
ILE = 1
LEU = 1
LYS = 1
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 5
R2 = 1
R3 = 0
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ALA = 1
ARG = 1
PRO = 3
VAL = 1

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
ARG = 2
ASN = 1
ASP = 2
CYS = 1
GLN = 1
GLY = 5
HIS = 2
ILE = 1
LEU = 3
LYS = 1
PRO = 2
SER = 2
TRP = 1
TYR = 2

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 12
R2 = 3
R3 = 5
R4 = 2
R5 = 5
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 3
CYS = 1
GLN = 1
GLY = 2
PRO = 3

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 8
R2 = 0
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 1
ARG = 1
CYS = 1
GLN = 1
GLY = 4
SER = 1

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 5
R2 = 0
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ALA = 2
ASP = 1
GLU = 1
LEU = 1
SER = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
LYS = 1
SER = 3
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 0
R2 = 1
R3 = 4
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
CYS = 1
GLU = 1
ILE = 1
LEU = 1
LYS = 2
SER = 2
THR = 2
VAL = 3

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 6
R2 = 0
R3 = 6
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KBC.RESIDUES]
ALA = 1
GLU = 2
LEU = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KBC.CLASS]
R1 = 3
R2 = 0
R3 = 1
R4 = 2
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBD.RESIDUES]
ALA = 1
ASN = 1
ASP = 1
CYS = 1
GLY = 1
LEU = 1
LYS = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KBD.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBE.RESIDUES]
GLU = 1
HIS = 1
LEU = 2
PRO = 1
SER = 2

[RESULTS.FREQUENCY.KBE.CLASS]
R1 = 3
R2 = 0
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBF.RESIDUES]
GLN = 1
LEU = 2
SER = 1

[RESULTS.FREQUENCY.KBF.CLASS]
R1 = 2
R2 = 0
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBG.RESIDUES]
ALA = 2
ASP = 2
CYS = 1
GLU = 2
GLY = 2
LEU = 7
PHE = 1
PRO = 2
SER = 4
THR = 1

[RESULTS.FREQUENCY.KBG.CLASS]
R1 = 13
R2 = 1
R3 = 6
R4 = 4
R5 = 0
RX = 0
