# pyKVFinder results

[FILES]
INPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/fixed/186_arv7.pdb"
OUTPUT = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/arv7/from_ensemble/cavity_186_arv7.pdb"
HYDROPATHY = "/Users/pantelispanka/miniconda3/envs/docking-examples/cavity_finder/test/arv7_data/hydropathy.pdb"

[PARAMETERS]
STEP = 0.6

[RESULTS.VOLUME]
KAA = 104.33
KAB = 104.11
KAC = 44.06
KAD = 30.46
KAE = 8.21
KAF = 495.72
KAG = 11.88
KAH = 53.78
KAI = 12.53
KAJ = 68.69
KAK = 24.84
KAL = 20.3
KAM = 118.8
KAN = 23.11
KAO = 53.14
KAP = 61.78
KAQ = 70.63
KAR = 36.5
KAS = 12.96
KAT = 135.22
KAU = 98.06
KAV = 97.63
KAW = 88.13
KAX = 689.69
KAY = 309.74
KAZ = 15.98
KBA = 16.42
KBB = 9.72

[RESULTS.AREA]
KAA = 128.75
KAB = 99.88
KAC = 62.84
KAD = 59.16
KAE = 12.19
KAF = 532.4
KAG = 11.17
KAH = 92.52
KAI = 15.83
KAJ = 70.2
KAK = 36.95
KAL = 35.72
KAM = 112.24
KAN = 25.17
KAO = 69.16
KAP = 45.83
KAQ = 52.26
KAR = 25.7
KAS = 8.6
KAT = 157.31
KAU = 110.67
KAV = 102.67
KAW = 91.07
KAX = 519.51
KAY = 242.7
KAZ = 19.55
KBA = 22.25
KBB = 24.19

[RESULTS.MAX_DEPTH]
KAA = 3.23
KAB = 2.4
KAC = 2.16
KAD = 1.34
KAE = 0.6
KAF = 6.03
KAG = 0.6
KAH = 3.7
KAI = 0.6
KAJ = 2.16
KAK = 1.7
KAL = 1.8
KAM = 3.23
KAN = 1.47
KAO = 2.81
KAP = 1.04
KAQ = 1.8
KAR = 0.6
KAS = 0.6
KAT = 4.24
KAU = 3.29
KAV = 2.47
KAW = 2.47
KAX = 4.33
KAY = 3.5
KAZ = 0.85
KBA = 1.2
KBB = 0.6

[RESULTS.AVG_DEPTH]
KAA = 1.04
KAB = 0.73
KAC = 0.96
KAD = 0.42
KAE = 0.14
KAF = 1.98
KAG = 0.1
KAH = 1.32
KAI = 0.06
KAJ = 0.6
KAK = 0.49
KAL = 0.5
KAM = 0.99
KAN = 0.41
KAO = 0.85
KAP = 0.24
KAQ = 0.5
KAR = 0.19
KAS = 0.09
KAT = 0.97
KAU = 0.88
KAV = 0.97
KAW = 0.63
KAX = 0.78
KAY = 0.79
KAZ = 0.23
KBA = 0.25
KBB = 0.11

[RESULTS.AVG_HYDROPATHY]
KAA = 0.03
KAB = -0.02
KAC = -0.85
KAD = 0.34
KAE = 0.55
KAF = 0.03
KAG = 1.61
KAH = 0.5
KAI = -0.22
KAJ = 1.13
KAK = 0.6
KAL = -0.09
KAM = -0.14
KAN = -0.1
KAO = 0.21
KAP = 0.49
KAQ = -0.46
KAR = -0.57
KAS = -0.35
KAT = -0.26
KAU = 0.12
KAV = -0.5
KAW = -0.3
KAX = 0.77
KAY = -0.03
KAZ = -0.77
KBA = -0.49
KBB = 0.11
EisenbergWeiss = [ -1.42, 2.6,]

[RESULTS.RESIDUES]
KAA = [ [ "583", " ", "PHE",], [ "584", " ", "PHE",], [ "586", " ", "ARG",], [ "587", " ", "ALA",], [ "594", " ", "TYR",], [ "609", " ", "ARG",], [ "610", " ", "LYS",], [ "612", " ", "CYS",], [ "613", " ", "PRO",], [ "615", " ", "CYS",], [ "616", " ", "ARG",], [ "617", " ", "LEU",],]
KAB = [ [ "479", " ", "ALA",], [ "480", " ", "PRO",], [ "481", " ", "TYR",], [ "482", " ", "GLY",], [ "485", " ", "ARG",], [ "495", " ", "SER",], [ "496", " ", "ASP",], [ "497", " ", "PHE",], [ "498", " ", "THR",],]
KAC = [ [ "584", " ", "PHE",], [ "587", " ", "ALA",], [ "588", " ", "ALA",], [ "617", " ", "LEU",], [ "620", " ", "CYS",], [ "621", " ", "TYR",], [ "625", " ", "MET",],]
KAD = [ [ "572", " ", "TYR",], [ "573", " ", "GLY",], [ "624", " ", "GLY",], [ "626", " ", "THR",], [ "631", " ", "PHE",], [ "632", " ", "ARG",], [ "633", " ", "VAL",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",],]
KAE = [ [ "480", " ", "PRO",], [ "508", " ", "MET",], [ "509", " ", "VAL",], [ "511", " ", "ARG",],]
KAF = [ [ "525", " ", "GLY",], [ "526", " ", "PRO",], [ "529", " ", "ASP",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "557", " ", "GLN",], [ "558", " ", "LYS",], [ "559", " ", "THR",], [ "560", " ", "CYS",], [ "561", " ", "LEU",], [ "562", " ", "ILE",], [ "563", " ", "CYS",], [ "564", " ", "GLY",], [ "569", " ", "GLY",], [ "570", " ", "CYS",], [ "574", " ", "ALA",], [ "575", " ", "LEU",], [ "604", " ", "ILE",], [ "619", " ", "LYS",], [ "622", " ", "GLU",], [ "623", " ", "ALA",], [ "632", " ", "ARG",], [ "634", " ", "GLY",], [ "635", " ", "ASN",], [ "636", " ", "CYS",], [ "637", " ", "LYS",], [ "638", " ", "HIS",], [ "639", " ", "LEU",], [ "640", " ", "LYS",], [ "641", " ", "MET",], [ "642", " ", "THR",], [ "643", " ", "ARG",],]
KAG = [ [ "475", " ", "ALA",], [ "511", " ", "ARG",], [ "512", " ", "VAL",],]
KAH = [ [ "596", " ", "CYS",], [ "597", " ", "ALA",], [ "598", " ", "SER",], [ "599", " ", "ARG",], [ "600", " ", "ASN",], [ "601", " ", "ASP",], [ "602", " ", "CYS",], [ "603", " ", "THR",], [ "604", " ", "ILE",], [ "614", " ", "SER",], [ "615", " ", "CYS",], [ "618", " ", "ARG",], [ "619", " ", "LYS",],]
KAI = [ [ "481", " ", "TYR",], [ "498", " ", "THR",], [ "499", " ", "ALA",], [ "506", " ", "GLY",], [ "508", " ", "MET",], [ "509", " ", "VAL",],]
KAJ = [ [ "537", " ", "ASP",], [ "539", " ", "ARG",], [ "540", " ", "LEU",], [ "548", " ", "LEU",], [ "549", " ", "PRO",], [ "550", " ", "ILE",], [ "551", " ", "ASP",], [ "552", " ", "TYR",], [ "553", " ", "TYR",], [ "554", " ", "PHE",],]
KAK = [ [ "526", " ", "PRO",], [ "529", " ", "ASP",], [ "530", " ", "SER",], [ "531", " ", "TYR",], [ "532", " ", "SER",], [ "533", " ", "GLY",], [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "637", " ", "LYS",],]
KAL = [ [ "534", " ", "PRO",], [ "535", " ", "TYR",], [ "536", " ", "GLY",], [ "537", " ", "ASP",], [ "553", " ", "TYR",], [ "554", " ", "PHE",], [ "555", " ", "PRO",], [ "558", " ", "LYS",], [ "567", " ", "ALA",],]
KAM = [ [ "432", " ", "SER",], [ "435", " ", "TRP",], [ "436", " ", "HIS",], [ "437", " ", "THR",], [ "438", " ", "LEU",], [ "439", " ", "PHE",], [ "440", " ", "THR",], [ "441", " ", "ALA",], [ "442", " ", "GLU",], [ "443", " ", "GLU",], [ "444", " ", "GLY",], [ "445", " ", "GLN",], [ "446", " ", "LEU",], [ "447", " ", "TYR",],]
KAN = [ [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "408", " ", "TYR",], [ "409", " ", "GLY",], [ "410", " ", "ASP",], [ "411", " ", "LEU",],]
KAO = [ [ "394", " ", "ASP",], [ "395", " ", "TYR",], [ "399", " ", "TRP",], [ "402", " ", "ALA",], [ "403", " ", "ALA",], [ "404", " ", "ALA",], [ "405", " ", "GLN",], [ "406", " ", "CYS",], [ "407", " ", "ARG",], [ "410", " ", "ASP",],]
KAP = [ [ "316", " ", "TYR",], [ "318", " ", "LYS",], [ "319", " ", "GLY",], [ "321", " ", "GLU",], [ "322", " ", "GLY",], [ "323", " ", "GLU",], [ "324", " ", "SER",], [ "325", " ", "LEU",], [ "326", " ", "GLY",], [ "327", " ", "CYS",],]
KAQ = [ [ "366", " ", "ASN",], [ "367", " ", "PHE",], [ "368", " ", "PRO",], [ "369", " ", "LEU",], [ "381", " ", "PRO",], [ "382", " ", "HIS",],]
KAR = [ [ "341", " ", "LEU",], [ "342", " ", "PRO",], [ "343", " ", "SER",], [ "346", " ", "SER",], [ "347", " ", "LEU",], [ "348", " ", "TYR",],]
KAS = [ [ "270", " ", "ALA",], [ "271", " ", "PRO",], [ "272", " ", "LEU",], [ "273", " ", "LEU",], [ "274", " ", "GLY",], [ "280", " ", "ARG",],]
KAT = [ [ "239", " ", "LEU",], [ "244", " ", "SER",], [ "245", " ", "VAL",], [ "248", " ", "GLY",], [ "249", " ", "LEU",], [ "250", " ", "GLY",], [ "251", " ", "VAL",], [ "254", " ", "LEU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "258", " ", "SER",], [ "259", " ", "PRO",], [ "260", " ", "GLY",], [ "261", " ", "GLU",], [ "262", " ", "GLN",], [ "263", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",],]
KAU = [ [ "231", " ", "THR",], [ "232", " ", "ILE",], [ "233", " ", "SER",], [ "234", " ", "ASP",], [ "235", " ", "ASN",], [ "236", " ", "ALA",], [ "237", " ", "LYS",], [ "238", " ", "GLU",], [ "239", " ", "LEU",], [ "240", " ", "CYS",], [ "254", " ", "LEU",], [ "255", " ", "GLU",], [ "256", " ", "HIS",], [ "257", " ", "LEU",], [ "264", " ", "ARG",], [ "265", " ", "GLY",],]
KAV = [ [ "166", " ", "LEU",], [ "174", " ", "LEU",], [ "175", " ", "SER",], [ "177", " ", "CYS",], [ "181", " ", "LEU",], [ "182", " ", "LYS",], [ "183", " ", "ASP",], [ "184", " ", "ILE",], [ "185", " ", "LEU",], [ "186", " ", "SER",], [ "187", " ", "GLU",], [ "189", " ", "SER",],]
KAW = [ [ "162", " ", "SER",], [ "163", " ", "THR",], [ "164", " ", "LEU",], [ "165", " ", "SER",], [ "166", " ", "LEU",], [ "167", " ", "LEU",], [ "170", " ", "THR",], [ "171", " ", "PHE",], [ "175", " ", "SER",], [ "187", " ", "GLU",], [ "188", " ", "ALA",], [ "189", " ", "SER",],]
KAX = [ [ "56", " ", "LEU",], [ "57", " ", "LEU",], [ "59", " ", "GLN",], [ "60", " ", "GLN",], [ "61", " ", "GLN",], [ "64", " ", "GLN",], [ "65", " ", "GLN",], [ "66", " ", "GLN",], [ "67", " ", "GLN",], [ "68", " ", "GLN",], [ "69", " ", "GLN",], [ "70", " ", "GLN",], [ "71", " ", "GLN",], [ "72", " ", "GLN",], [ "73", " ", "GLN",], [ "74", " ", "GLN",], [ "75", " ", "GLN",], [ "76", " ", "GLN",], [ "77", " ", "GLN",], [ "78", " ", "GLN",], [ "79", " ", "GLN",], [ "80", " ", "GLN",], [ "82", " ", "THR",], [ "84", " ", "PRO",], [ "85", " ", "ARG",], [ "86", " ", "GLN",], [ "87", " ", "GLN",], [ "90", " ", "GLN",], [ "91", " ", "GLN",], [ "98", " ", "GLN",], [ "99", " ", "ALA",], [ "100", " ", "HIS",], [ "101", " ", "ARG",], [ "102", " ", "ARG",], [ "103", " ", "GLY",], [ "105", " ", "THR",], [ "138", " ", "ALA",], [ "139", " ", "VAL",], [ "146", " ", "PRO",],]
KAY = [ [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "33", " ", "VAL",], [ "34", " ", "ILE",], [ "35", " ", "GLN",], [ "36", " ", "ASN",], [ "37", " ", "PRO",], [ "38", " ", "GLY",], [ "39", " ", "PRO",], [ "40", " ", "ARG",], [ "41", " ", "HIS",], [ "42", " ", "PRO",], [ "43", " ", "GLU",], [ "44", " ", "ALA",], [ "45", " ", "ALA",], [ "46", " ", "SER",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "60", " ", "GLN",], [ "134", " ", "GLU",], [ "135", " ", "PRO",], [ "138", " ", "ALA",], [ "139", " ", "VAL",], [ "140", " ", "ALA",], [ "141", " ", "ALA",],]
KAZ = [ [ "50", " ", "PRO",], [ "51", " ", "GLY",], [ "52", " ", "ALA",], [ "54", " ", "LEU",], [ "55", " ", "LEU",], [ "56", " ", "LEU",], [ "58", " ", "GLN",],]
KBA = [ [ "24", " ", "GLN",], [ "26", " ", "LEU",], [ "27", " ", "PHE",], [ "28", " ", "GLN",], [ "29", " ", "SER",], [ "30", " ", "VAL",], [ "40", " ", "ARG",],]
KBB = [ [ "15", " ", "PRO",], [ "18", " ", "THR",], [ "19", " ", "TYR",], [ "20", " ", "ARG",], [ "21", " ", "GLY",], [ "22", " ", "ALA",], [ "23", " ", "PHE",], [ "24", " ", "GLN",],]

[RESULTS.FREQUENCY.KAA.RESIDUES]
ALA = 1
ARG = 3
CYS = 2
LEU = 1
LYS = 1
PHE = 2
PRO = 1
TYR = 1

[RESULTS.FREQUENCY.KAA.CLASS]
R1 = 3
R2 = 3
R3 = 2
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAB.RESIDUES]
ALA = 1
ARG = 1
ASP = 1
GLY = 1
PHE = 1
PRO = 1
SER = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KAB.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAC.RESIDUES]
ALA = 2
CYS = 1
LEU = 1
MET = 1
PHE = 1
TYR = 1

[RESULTS.FREQUENCY.KAC.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAD.RESIDUES]
ARG = 1
ASN = 1
CYS = 1
GLY = 3
PHE = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAD.CLASS]
R1 = 4
R2 = 2
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAE.RESIDUES]
ARG = 1
MET = 1
PRO = 1
VAL = 1

[RESULTS.FREQUENCY.KAE.CLASS]
R1 = 2
R2 = 0
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAF.RESIDUES]
ALA = 2
ARG = 2
ASN = 1
ASP = 1
CYS = 4
GLN = 1
GLU = 1
GLY = 4
HIS = 1
ILE = 2
LEU = 3
LYS = 4
MET = 1
PRO = 2
THR = 2
TYR = 1

[RESULTS.FREQUENCY.KAF.CLASS]
R1 = 13
R2 = 1
R3 = 9
R4 = 2
R5 = 7
RX = 0

[RESULTS.FREQUENCY.KAG.RESIDUES]
ALA = 1
ARG = 1
VAL = 1

[RESULTS.FREQUENCY.KAG.CLASS]
R1 = 2
R2 = 0
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAH.RESIDUES]
ALA = 1
ARG = 2
ASN = 1
ASP = 1
CYS = 3
ILE = 1
LYS = 1
SER = 2
THR = 1

[RESULTS.FREQUENCY.KAH.CLASS]
R1 = 2
R2 = 0
R3 = 7
R4 = 1
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAI.RESIDUES]
ALA = 1
GLY = 1
MET = 1
THR = 1
TYR = 1
VAL = 1

[RESULTS.FREQUENCY.KAI.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAJ.RESIDUES]
ARG = 1
ASP = 2
ILE = 1
LEU = 2
PHE = 1
PRO = 1
TYR = 2

[RESULTS.FREQUENCY.KAJ.CLASS]
R1 = 4
R2 = 3
R3 = 0
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAK.RESIDUES]
ASP = 1
GLY = 1
LYS = 1
PRO = 2
SER = 2
TYR = 2

[RESULTS.FREQUENCY.KAK.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAL.RESIDUES]
ALA = 1
ASP = 1
GLY = 1
LYS = 1
PHE = 1
PRO = 2
TYR = 2

[RESULTS.FREQUENCY.KAL.CLASS]
R1 = 4
R2 = 3
R3 = 0
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAM.RESIDUES]
ALA = 1
GLN = 1
GLU = 2
GLY = 1
HIS = 1
LEU = 2
PHE = 1
SER = 1
THR = 2
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAM.CLASS]
R1 = 4
R2 = 3
R3 = 4
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAN.RESIDUES]
ARG = 1
ASP = 1
CYS = 1
GLN = 1
GLY = 1
LEU = 1
TYR = 1

[RESULTS.FREQUENCY.KAN.CLASS]
R1 = 2
R2 = 1
R3 = 2
R4 = 1
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAO.RESIDUES]
ALA = 3
ARG = 1
ASP = 2
CYS = 1
GLN = 1
TRP = 1
TYR = 1

[RESULTS.FREQUENCY.KAO.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAP.RESIDUES]
CYS = 1
GLU = 2
GLY = 3
LEU = 1
LYS = 1
SER = 1
TYR = 1

[RESULTS.FREQUENCY.KAP.CLASS]
R1 = 4
R2 = 1
R3 = 2
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAQ.RESIDUES]
ASN = 1
HIS = 1
LEU = 1
PHE = 1
PRO = 2

[RESULTS.FREQUENCY.KAQ.CLASS]
R1 = 3
R2 = 1
R3 = 1
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAR.RESIDUES]
LEU = 2
PRO = 1
SER = 2
TYR = 1

[RESULTS.FREQUENCY.KAR.CLASS]
R1 = 3
R2 = 1
R3 = 2
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAS.RESIDUES]
ALA = 1
ARG = 1
GLY = 1
LEU = 2
PRO = 1

[RESULTS.FREQUENCY.KAS.CLASS]
R1 = 5
R2 = 0
R3 = 0
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAT.RESIDUES]
ARG = 1
GLN = 1
GLU = 1
GLY = 4
HIS = 1
LEU = 5
PRO = 1
SER = 2
VAL = 2

[RESULTS.FREQUENCY.KAT.CLASS]
R1 = 12
R2 = 0
R3 = 3
R4 = 1
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAU.RESIDUES]
ALA = 1
ARG = 1
ASN = 1
ASP = 1
CYS = 1
GLU = 2
GLY = 1
HIS = 1
ILE = 1
LEU = 3
LYS = 1
SER = 1
THR = 1

[RESULTS.FREQUENCY.KAU.CLASS]
R1 = 6
R2 = 0
R3 = 4
R4 = 3
R5 = 3
RX = 0

[RESULTS.FREQUENCY.KAV.RESIDUES]
ASP = 1
CYS = 1
GLU = 1
ILE = 1
LEU = 4
LYS = 1
SER = 3

[RESULTS.FREQUENCY.KAV.CLASS]
R1 = 5
R2 = 0
R3 = 4
R4 = 2
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KAW.RESIDUES]
ALA = 1
GLU = 1
LEU = 3
PHE = 1
SER = 4
THR = 2

[RESULTS.FREQUENCY.KAW.CLASS]
R1 = 4
R2 = 1
R3 = 6
R4 = 1
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KAX.RESIDUES]
ALA = 2
ARG = 3
GLN = 25
GLY = 1
HIS = 1
LEU = 2
PRO = 2
THR = 2
VAL = 1

[RESULTS.FREQUENCY.KAX.CLASS]
R1 = 8
R2 = 0
R3 = 27
R4 = 0
R5 = 4
RX = 0

[RESULTS.FREQUENCY.KAY.RESIDUES]
ALA = 5
ARG = 1
ASN = 1
GLN = 2
GLU = 2
GLY = 1
HIS = 1
ILE = 1
LEU = 2
PRO = 4
SER = 2
VAL = 3

[RESULTS.FREQUENCY.KAY.CLASS]
R1 = 16
R2 = 0
R3 = 5
R4 = 2
R5 = 2
RX = 0

[RESULTS.FREQUENCY.KAZ.RESIDUES]
ALA = 1
GLN = 1
GLY = 1
LEU = 3
PRO = 1

[RESULTS.FREQUENCY.KAZ.CLASS]
R1 = 6
R2 = 0
R3 = 1
R4 = 0
R5 = 0
RX = 0

[RESULTS.FREQUENCY.KBA.RESIDUES]
ARG = 1
GLN = 2
LEU = 1
PHE = 1
SER = 1
VAL = 1

[RESULTS.FREQUENCY.KBA.CLASS]
R1 = 2
R2 = 1
R3 = 3
R4 = 0
R5 = 1
RX = 0

[RESULTS.FREQUENCY.KBB.RESIDUES]
ALA = 1
ARG = 1
GLN = 1
GLY = 1
PHE = 1
PRO = 1
THR = 1
TYR = 1

[RESULTS.FREQUENCY.KBB.CLASS]
R1 = 3
R2 = 2
R3 = 2
R4 = 0
R5 = 1
RX = 0
